### ISSUE TITLE
Unicorn creating separate folder on Item edit/creation

### ISSUE THREAD

**Issue by hemantjangra** [kamsar/Unicorn#100]
Hello,

This is regarding creation of separate folder and creating duplicate 'yml' file when trying to edit synced items.

In case of item edits and creating new items in Sitecore separate folder is getting created with parent-item id in parallel to grand parent on physical disk.

Even after Re serializing configuration, it is creating separate folder with parent item id and moving only certain items to that folder.

Also tried moving created yml files to correct location and sync back, but it gives up error pop up on editing items (second time).

Please help and suggest.

Thanks,
Hemant Kumar

**Comment by kamsar** [comment]
That's called a loopback path and its there to work around the Windows max
file path length. It's expected behavior.

The values used to determine when to loopback are in rainbow.config with
comments.

**Comment by hemantjangra** [comment]
Thanks a lot, missed that setting. It definitely helped.
