### ISSUE TITLE
Additional configuration flags

### ISSUE THREAD

**Issue by kamsar** [kamsar/Unicorn#105]
It might be nice to have some additional flags that would further segregate many-configurationed projects. For example:

* `explicitSyncOnly` => configuration is not synced when 'sync all' is used, and must be synced explicitly or included in a list of configs to sync
* `maxConcurrency` => set the max number of threads to use when syncing or reserializing. Must be 1 if the config contains template items due to a Sitecore bug (see #80) but for content configs we can speed things up by allowing threading.
* `category` => organize the control panel by categories of configuration, possibly collapsed by default, for organizational purposes. Should also be able to flag all configs in a category for sync.

Anyone else got ideas? Feedback? At present this is just an idea.

**Comment by Eldblom** [comment]
The most pressing feature I would have for this is the ability to specify wildcards as sync targets - and have Unicorn sort out the dependencies and ordering.

Something like:  
`/unicorn.aspx?verb=Sync&configuration=*`  
or even:  
`/unicorn.aspx?verb=Sync&configuration=Foundation.*^Feature.*^Project.Common.Website^Project.Habitat.Website`

**Comment by demisx** [comment]
+1 We are in desperate need to be able to perform sync for all configurations available, i.e.:

```
unicorn.aspx?verb=Sync&configuration=All
```

**Comment by kamsar** [comment]
That is already available, just don't specify the configuration parameter
and that implies all configurations.

**Comment by demisx** [comment]
It is indeed! Thanks Kam.

**Comment by kamsar** [comment]
3.1.5 will have sync all available with a single click :grinning:

**Comment by Eldblom** [comment]
Would that be in the right order based on dependencies?

**Comment by kamsar** [comment]
Absolutely. Dependencies are resolved for all syncs.

**Comment by kamsar** [comment]
3.1.5 contains a sync all button with the URL mentioned above, as well as the maxConcurrency setting.
