### ISSUE TITLE
Feature request: Delete orphaned items

### ISSUE THREAD

**Issue by drachele** [kamsar/Unicorn#106]
Currently, if a template is removed by Unicorn, any items which are using this template are left as orphaned items in the database.

Would be great to have the option to allow Unicorn to remove these automatically, or fail the sync if it tries to remove a template which is being referenced by items. The only way to remove these items at the moment is to delete them via a Sitecore Powershell script.

Would something like this be possible?

Thanks,
Dan.

**Comment by kamsar** [comment]
It would be possible to implement, but overall not something I would ship. 

Suppose, for example, you were working on a feature branch workflow and you switched to a branch to review code where a template you'd been working on didn't exist. With this setting, Unicorn would reach out and destroy any test content, etc that contained the other branch's template and you'd have no recourse other than manual restore from recycle bin.

Or imagine a bad commit that removed a core content template that made its way to production. Bye bye website?
