### ISSUE TITLE
Use of hyphens in security check violates standard item rules

### ISSUE THREAD

**Issue by dsolovay** [kamsar/Unicorn#111]
In order to get sync to work, it is necessary to allow hyphens in item names, which are not enabled by default, due to this OOTB config setting:

`<setting name="InvalidItemNameChars" value="-\/:?"<>|[]"/>`

~~Ideally, item sync would work with OOTB config settings.~~ [See https://github.com/kamsar/Unicorn/issues/111#issuecomment-180600382]

**Comment by kamsar** [comment]
Hyphen is not out of the box though? There are core DB items that have hyphens in them, or at least there used to be.

**Comment by kamsar** [comment]
This has been fixed, challenge item names will now be GUIDs without hyphens. If Sitecore installs disallow a-f, 0-9 they have larger problems :)

And YES, I wrote a test https://github.com/kamsar/MicroCHAP/commit/3c16c1a932e72ebc4c0604e55350d2af5cea1f4a :grinning: 

This'll be in 3.1.2, which I'm planning to release this morning with another fix for stuff I'm doing.

**Comment by dsolovay** [comment]
I stand corrected. I checked a fresh install, and there is no restriction on hyphens:

`<setting name="InvalidItemNameChars" value="\/:?"<>|[]"/>`

**Comment by kamsar** [comment]
Fixed in 3.1.2
