### ISSUE TITLE
Auto publishing not publishing items

### ISSUE THREAD

**Issue by TheCodeKing** [kamsar/Unicorn#114]
We have an issue with some items not being auto published during sync. 

We are redeploying a large number of items to an empty Sitecore instance, and found that deeper nested items aren't publishing their children. We also found that * items higher up in the tree are also not being published. A manual publish does publish as expected.

**Comment by TheCodeKing** [comment]
Further investigation suggests its only affecting a specific language. All English items are being auto-published, but not en-US which was also deployed via Unicorn previously. 

Is there anything special we need to do to deploy all language versions of content items? Unicorn is correctly serialising the en-US versions to disk and this is the only language version available for those items.

**Comment by kamsar** [comment]
So like the publish is only running against en versions but not en-US?
Seems potentially plausible. I'll look into it.

**Comment by TheCodeKing** [comment]
Yea that's right, no en-US content is being auto-published however en is.

**Comment by kamsar** [comment]
Good news: this was pretty easy to reproduce and will be fixed in the next version.

**Comment by TheCodeKing** [comment]
Great thanks!

**Comment by kamsar** [comment]
Fixed in 3.1.4
