### ISSUE TITLE
Removing SQL Entirely?

### ISSUE THREAD

**Issue by geoffreysmith** [kamsar/Unicorn#115]
I'm trying to remove the SQL dependency entirely and use transparent sync as my only dataprovider. If I remember from some several years ago, there was a MongoDb dataprovider that ran into weird issues where even though it *looks* like you can replace Sitecore's SQL dataprovider, there were some, what I assume, hardcoded assumptions of using SQL. See here:

http://hermanussen.eu/sitecore/wordpress/2012/05/making-sitecore-faster-with-mongodb/

And the issues here about publishing failing:

https://github.com/pbering/SitecoreData/issues

I played around with this today but was wondering if you made any headway.

**Comment by kamsar** [comment]
I have never tried this. It might be theoretically possible, but
transparent sync does not implement some aspects of sitecores database,
such as links database and archives, that would cause some things to fail.

**Comment by Eldblom** [comment]
Alen Pelin has a project for this purpose: https://github.com/Sitecore/Sitecore.NoSQL
