### ISSUE TITLE
ERROR: Could not get pipeline: unicornReserializeComplete 

### ISSUE THREAD

**Issue by Sivalingaamorthy** [kamsar/Unicorn#118]
Hi,

I am getting below error, do we have any solution. I am trying to serialize the media library contents.

The output is getting generated, but not sure this is complete. 

Can you suggest a solution / fix for the same.

-------------------------------
Hydra Media Library is being reserialized.
[D] Clearing existing items from Serialization File System Data Store (if any)
[U] Serializing included items under root master:/sitecore/media library/Globus (56bfa64d-7e07-466f-8b01-9eb003aa5e1a)
ERROR: Could not get pipeline: unicornReserializeComplete (domain: ) (System.InvalidOperationException)
at Sitecore.Pipelines.CorePipeline.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists) 
at Unicorn.ControlPanel.Pipelines.UnicornControlPanelRequest.ReserializeVerb.Process(IProgressStatus progress, ILogger additionalLogger)

**Comment by kamsar** [comment]
You probably recently upgraded to 3.1.2, which added this pipeline, but had a modified config file and chose to not overwrite, thus losing the definition for the new pipeline. Merge your config with the standard config files in the git repo and that should solve your problem (under src/Unicorn/Standard Config Files)
