### ISSUE TITLE
Fallback option ignored: extra versions created

### ISSUE THREAD

**Issue by WizX20** [kamsar/Unicorn#123]
When creating a template with 'Enable item fallback' enabled in the '__Standard values' of the item template. Additional versions are created on sync for items based on the template.

Steps to reproduce:

1. Create a new template in English (en) with at least one field (Title);
2. Create standard values for the template and set the option 'Enable item fallback' in the tab Advanced to true;
3. Add a new language in /sitecore/system/Languages and set the 'Fallback Language' to English (en);
4. Create a new item based on the template in English (en) and fill out the field (Title);
5. Switch to the other language you created, you will notice Sitecore will show the text 'Fallback version' in the version dropdown and the fields of the items will be disabled and showing the values of the fallback item (en);
6. Synch your changes from dev. to the next environment (test);
7. Open the item on the next environment (test): Notice that for every language a version has been created instead of just the English version and a fallback for the other language.

The last two steps are still a bit sketchy, I'm not exactly sure when and how the extra versions are created. Perhaps also republish your templates in all languages after this.

**Comment by kamsar** [comment]
This is occurring because `item.GetVersions(true)` on an item with fallback enabled also returns all fallback versions - even if they do not physically exist. Unicorn thus writes all these versions to disk, which is wrong.

Fixing it is a bit touchy however. The version has an `IsFallback` property, however Sitecore < 8.1 (which Unicorn should remain compatible with) does not have this property.

**Comment by kamsar** [comment]
It seems to work fine if I build against 8.1 kernel, but add a programmatic Sitecore version check around the call to `IsFallback` (verified with 7.2). This will be fixed in the next version.

**Comment by kamsar** [comment]
This should be fixed in Unicorn 3.1.5-beta01, available on NuGet.

**Comment by kamsar** [comment]
Unicorn 3.1.5 has been released with this fix. Closing the issue. If you find it again, please reopen.
