### ISSUE TITLE
Production unicorn configuration - sync without serialise

### ISSUE THREAD

**Issue by TheCodeKing** [kamsar/Unicorn#131]
When we deploy using unicorn to our environments, we take changes serialised to disk from our development server and sync to our target instance.

What's the recommended way to disable the serialisation data provider for production servers, so we can still sync content from disk but not serialise further changes to disk?

**Comment by kamsar** [comment]
https://github.com/kamsar/Unicorn/blob/master/src/Unicorn/Standard%20Config%20Files/Unicorn.DataProvider.config#L6

**Comment by TheCodeKing** [comment]
Ah perfect, thank you!
