### ISSUE TITLE
Issue with changing sortorder | Unicorn 3.1.5 and transparent sync enabled

### ISSUE THREAD

**Issue by stefansluijter** [kamsar/Unicorn#132]
Copied from SitecoreChat slack:

stefan.sluijter [3:14 PM] 
@kamsar: We've encountered a problem when changing the sortorder in one of my templates folder. (Simply moving a folder on alphabetical order :confused: )
We are running on version 3.1.5 with transparent sync enabled. 
To reproduce the issue: All i did was moving a folder above another(below the root of the folder) . When I refreshed the tree the only folder visible was that folder i just moved.

Steps i did to fix the issue:

- Move templates out of the 'corrupted' folder
- Delete the folder
- Refresh
_ All templates appear again
- Create the deleted folder
- Move templates back

kamsar [3:16 PM] 
so to cause the issue you moved an item up the tree (e.g. /foo/bar/baz -> /foo/baz)?

[3:17] 
or moving the sort order within one folder?

stefan.sluijter [3:19 PM] 
We are using habitat so we work with features.

So this is what i did:

​_Before:_​
>Templates
>>Features
>>>Folder2
>>>Folder3
>>>Folder1

​_After:_​
>Templates
>>Features
>>>Folder1
>>>Folder2
>>>Folder3

[3:20] 
_Result_
>Templates
>>Features
>>>Folder1

**Comment by kamsar** [comment]
I'm trying to reproduce this but having trouble doing so.

I've got a site on 3.1.5 that has templates and renderings both under transparent sync. I've reordered both template and rendering items, both by dragging them around as well as using the 'up/down' buttons, and have not experienced any disappearance of items.

The files on disk also have their sort order fields updated as expected.

**Comment by kamsar** [comment]
I've also tried with and without data cache enabled. Do you have any insight on what I'm missing here?

**Comment by stefansluijter** [comment]
Hello Kamsar, 

First of all sorry for my late reply, only saw your message a couple of minutes a go.
I'm worried and happy at the same time that you are not able to reproduce it.
Unfortunately i don't have more information regarding this issue.
In my opinion you can close the case as everything has been working fine since i've done the steps above.


Thanks for the work :)

**Comment by kamsar** [comment]
Closing per above and Slack conversation
