### ISSUE TITLE
Less-than-optimal error warning when patching configs in wrong order

### ISSUE THREAD

**Issue by cassidydotdk** [kamsar/Unicorn#135]
So I basically have a config patch file sitting on App_Config\Include, patching the location of the targetDataStore. However, since this file is patched BEFORE the vanilla files sitting in the App_Config\Include\Unicorn folder, the patch ends up messing up Unicorn badly - to the point where Sitecore cannot start at all; not even ShowConfig.aspx.

It is, of course, a mis-configuration on the user part - but would be nice if the resulting error message could be more indicative of what's going on. As what is output now, doesn't give much of a clue ;-)

Here's the stack trace:

Server Error in '/' Application.

Cannot activate Rainbow.Storage.SerializationFileSystemDataStore, constructor param 'useDataCache' (Boolean). The type 'Boolean' is probably not registered, or may need to be an explicit unmapped parameter (as an XML attribute on the type registration). Inner message: Cannot construct System.Boolean because it has no constructor!

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Unicorn.Configuration.MicroResolutionException: Cannot activate Rainbow.Storage.SerializationFileSystemDataStore, constructor param 'useDataCache' (Boolean). The type 'Boolean' is probably not registered, or may need to be an explicit unmapped parameter (as an XML attribute on the type registration). Inner message: Cannot construct System.Boolean because it has no constructor!

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[MicroResolutionException: Cannot activate Rainbow.Storage.SerializationFileSystemDataStore, constructor param 'useDataCache' (Boolean). The type 'Boolean' is probably not registered, or may need to be an explicit unmapped parameter (as an XML attribute on the type registration). Inner message: Cannot construct System.Boolean because it has no constructor!]
   Unicorn.Configuration.MicroConfiguration.Activate(Type type, KeyValuePair`2[] unmappedConstructorParameters) +1384
   Unicorn.Configuration.<>c__DisplayClass7_0`1.<RegisterExpectedConfigType>b__2() +38
   System.Lazy`1.CreateValue() +709
   System.Lazy`1.LazyInitValue() +191
   Unicorn.Data.ConfigurationDataStore.RegisterForChanges(Action`2 actionOnChange) +19
   Unicorn.Data.DataProvider.UnicornDataProvider..ctor(ITargetDataStore targetDataStore, ISourceDataStore sourceDataStore, IPredicate predicate, IFieldFilter fieldFilter, IUnicornDataProviderLogger logger, IUnicornDataProviderConfiguration dataProviderConfiguration, ISyncConfiguration syncConfiguration, PredicateRootPathResolver rootPathResolver) +559
   lambda_method(Closure , Object[] ) +391
   Unicorn.Configuration.MicroConfiguration.Activate(Type type, KeyValuePair`2[] unmappedConstructorParameters) +825
   Unicorn.Configuration.MicroConfiguration.Resolve() +117
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +80
   System.Linq.Buffer`1..ctor(IEnumerable`1 source) +153
   System.Linq.Enumerable.ToArray(IEnumerable`1 source) +106
   Unicorn.Data.DataProvider.UnicornSqlServerDataProvider..ctor(String connectionString) +232

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +342
   Sitecore.Reflection.ReflectionUtil.CreateObject(Type type, Object[] parameters) +119
   Sitecore.Configuration.Factory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert) +103
   Sitecore.Configuration.Factory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +131
   Sitecore.Configuration.Factory.CreateObject(String configPath, String[] parameters, Boolean assert) +579
   Sitecore.Configuration.Factory.CreateFromReference(XmlNode configNode, String[] parameters, Boolean assert) +137
   Sitecore.Configuration.Factory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +109
   Sitecore.Configuration.Factory.GetInnerObject(XmlNode paramNode, String[] parameters, Boolean assert) +1013
   Sitecore.Configuration.Factory.AssignProperties(XmlNode configNode, String[] parameters, Object obj, Boolean assert, Boolean deferred, IFactoryHelper helper) +552
   Sitecore.Configuration.Factory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +275
   Sitecore.Configuration.Factory.CreateObject(String configPath, String[] parameters, Boolean assert) +579
   Sitecore.Configuration.Factory.GetDatabase(String name, Boolean assert) +144
   Sitecore.Configuration.Factory.GetDatabase(String name) +42
   Sitecore.Configuration.Factory.GetDatabases() +98
   Sitecore.Data.Managers.ItemManager.InitializeEventHandlers() +35
   (Object , Object[] ) +101
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +484
   (Object , Object[] ) +71
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +484
   Sitecore.Nexus.Web.HttpModule.Application_Start() +227
   Sitecore.Nexus.Web.HttpModule.Init(HttpApplication app) +673
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +618
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +402
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +343

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +579
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +112
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +712

**Comment by cassidydotdk** [comment]
Oh, and the patch file used, is exactly the same as Unicorn.CustomSerializationFolder.config.example. I just made a copy and moved it out of the Unicorn folder as it seemed "neater" ;-)

**Comment by kamsar** [comment]
There's not a really great way to fix this. The patch ends up adding two `<targetDataStore>` nodes (you can see it if you disable the data provider config), one of which is missing all the default attributes.

So I added a warning to that config file template. Most patches don't matter too much in terms of order, but this one does. It's generally a good practice to patch after the default though.

I use a 'zGlobal' and 'zSites' config setup for general patches and site specific stuff respectively. Works well for this.

**Comment by kamsar** [comment]
This is in 3.2
