### ISSUE TITLE
Include root, children, but not children of children

### ISSUE THREAD

**Issue by JeffDarchuk** [kamsar/Unicorn#138]
it would be nice to be able to specify a root node to include and have all children be included as well, but have the content deeper in the subtree be considered content.  This would be for shared content folders.

**Comment by kamsar** [comment]
To write this out, since we talked about this, the use case here is something like:

```
<include path="/foo">
    <exclude childrenOfPath="bar/* />
</include>
```

Expected output:
/foo = true
/foo/bar = true
/foo/bar/baz = true
/foo/bar/baz/quux = false

**Comment by kamsar** [comment]
There you go, even with tests you lazy bastard :grinning:
