### ISSUE TITLE
UnicornSqlServerDataProvider is always returning ChildIDs for a itemDefinition

### ISSUE THREAD

**Issue by MadsDue** [kamsar/Unicorn#141]
We are having some issues with getting our dataprovider (uCommerce) to work properly with the UnicornSqlServerDataProvider which extend from SqlServerDataProvider.
What happens is that when we have enabled unicorn and the UnicornSqlServerDataProvider, our dataprovider doesn’t provide any children to our uCommerce node because the context.CurrentResult is not null when it’s our dataprovider turn to provide children. 
I do not know must about Sitecore dataprovider, however I think this is cause by the GetChildIDs method in UnicornSqlServerDataProvider because it never returns null but instead an empty list if it can’t provide any children, because of this code: 
if (results.Count == 0)
{
                
    // get database children
    var baseIds = base.GetChildIDs(itemDefinition, context) ?? new IDList();

    // get additional children from Unicorn providers
    // e.g. for TpSync if the root item of a tree is not in the database
    // this allows us to inject that root as a child of the DB item
    foreach (var provider in UnicornDataProviders)
    {
        var providerResult = provider.GetAdditionalChildIds(itemDefinition, context);
        foreach (var result in providerResult)
        {
            if (!baseIds.Contains(result)) baseIds.Add(result);
        }
    }

   return baseIds;
}

I tried adding the below before return baseIds is called and it seems to do the trick. 
if(baseIds.Count == 0)
   return null;

Could you look at this to see if I’m totally wrong or there is a bug?

**Comment by cassidydotdk** [comment]
Can I ask; how are you guys setting up the chained providers?    No working example in any Sitecore documentation requires a null to be returned from GetChildIDs. In fact the opposite. Now I realise that this link is archeological, however I don't believe the Data Provider technology has changed much if at all since this was written.

https://sdn.sitecore.net/Developer/Integrating%20External%20Data%20Sources/Reference/DataProvider%20Methods/GetChildIDs.aspx

If chained providers are set up correctly, it should not matter what another provider in the chain returns. Or am I missing something?

**Comment by kamsar** [comment]
There is some precedent to returning null, for example in `SqlDataProvider` `GetChildIDs()`:

```
  if (prefetchData == null)
        return (IDList) null;
```

Rhino, whose data provider served as a template to Unicorn and used a chained data provider, returned null:

https://github.com/kamsar/Rhino/blob/master/src/Rhino/SerializationDataProvider.cs#L64

I think this can be safely fixed without causing any issues to return null. Refer to https://github.com/kamsar/Unicorn/blob/master/src/Unicorn/Data/DataProvider/UnicornSqlServerDataProvider.cs#L181

**Comment by kamsar** [comment]
I set it to return null and tested it, and things appear fine. This will be in the next release.

**Comment by kamsar** [comment]
Released in 3.3.1
