### ISSUE TITLE
Long item name rename duplicate yaml

### ISSUE THREAD

**Issue by JeffDarchuk** [kamsar/Unicorn#146]
I have a long named item that unicorn truncated, when i tried to rename it the yaml was duplicated thus getting an id collision.

**Comment by kamsar** [comment]
Where's my PR you lazy bastard :grinning:

**Comment by kamsar** [comment]
Fiiiine I'll fix it myself :stuck_out_tongue_closed_eyes: 

This will be fixed in the next version. Duplicate ID checks were too aggressive when renaming an item _to a subset of its former name_ (e.g. foo -> fo).

**Comment by kamsar** [comment]
Released in 3.3.1
