### ISSUE TITLE
Unicorn Integration with Courier 

### ISSUE THREAD

**Issue by Sivalingaamorthy** [kamsar/Unicorn#147]
Can you throw some light on the integration of Unicorn Integration with Courier for incremental package creation.

I did some research found this could be possible, but not found any practical sample, can you provide some reference.

**Comment by kamsar** [comment]
I didn't implement the Rainbow integration for Courier, and I do not personally use Courier as part of my build process. You might try the folks who have implemented it: 

https://github.com/adoprog/Sitecore-Courier/pull/14
https://github.com/adoprog/Sitecore-Courier/pull/17
