### ISSUE TITLE
Synchronize Items but not the Fields

### ISSUE THREAD

**Issue by Swissi** [kamsar/Unicorn#149]
Hi Kam

I am starting to use Unicorn in a brand new solution. I really achieved a lot by using it, so thanks alot :) (Gone are sitecore packages)

But i have some limits:
- In the content tree i have several "settings items". They include some global content/settings. This settings item is being used in my application (referring with item IDs). I want that the exact same item exists in my other environments, but i dont want that the fields are being synchronized. 

Example:

In the meta settings Item i have a field "Robots Content". Its a basic multiline field. So i want that Unicorn creates the Meta Settings Item , but i dont want that its overwriting its values (since the author could have changed it)

Is there a way to achieve it?

Thanks alot.

Dave

**Comment by kamsar** [comment]
http://kamsar.net/index.php/2015/10/Unicorn-3-0-Released/#New_Items_Only_Evaluator
