### ISSUE TITLE
Disable Serialize on other environments

### ISSUE THREAD

**Issue by Swissi** [kamsar/Unicorn#150]
Hi Kam

Is there a way to disable automatic serialisations by config? 

My use case:

On my local environment i want that items are being serialised. By using auto synch this is a very easy and good approach.

On my staging environment i don't want that items are being serialised. 
- I don't want a "Reserialize" option on the unicorn control panel
- I want to disable the automatic serialisation to files because its not needed.
- I just need "Sync" on the staging environment

One Reason:
- The problem is that through automated deployment, the folder where the YML files are being stored, the Unicorn process has no "Write" access and generates an Error in the sitecore content editor.

Is this achievable by config?

Thanks a lot

Regards from Switzerland

Dave

**Comment by kamsar** [comment]
Each config file has a comment as to what type of environments it should be enabled for. In this case you're looking for `Unicorn.DataProvider.config` to be disabled.

That will not disable reserializing, but will disable writing of updates.

**Comment by Swissi** [comment]
Thanks a lot. I didn't crawl through the comments of the config files, my bad. Perfect! :)
