### ISSUE TITLE
Spurious conflict warning in certain circumstances

### ISSUE THREAD

**Issue by kamsar** [kamsar/Unicorn#151]
See: https://github.com/cassidydotdk/Rainbow/commit/3acc34c1f2dbd1594338f3903da5a2527f891a6e

On occasion clearing checkbox fields or reverting a field to a blank standard value (right @cassidydotdk?) will result in a "conflict" due to the item reader ignoring empty valued fields.

We need to evaluate the possible side effects of this fix (maybe other spurious comparisons when fields don't exist?) and figure out a decent solution.

**Comment by cassidydotdk** [comment]
Actually, specifically, I had one checkbox field on a template; the stdval of the template was "empty" (so the checkbox was unchecked). When changing said checkbox in Sitecore Content Editor from "unchecked" to "checked"; Unicorn would throw a conflict warning. But when going from "checked" back to "unchecked", no such warning happened.

Upon investigation; when unchecking the value - everything went through normal execution flow, and the checkbox value was compared using the CheckboxFieldComparer. But when checking the value, it goes from "empty" (Sitecore default value for an unchecked checkbox) to "1" - however the "empty" value causes Rainbow to ignore the field value.

My proposed fix is; when getting the Sitecore field value; stdval and other defaults and fallbacks are ignored. So Rainbow only gets the actual value set for the specific item. Assuming it gets any value at all, this value should be considered significant. Before my proposed fix, Rainbow would ignore the value if it was null or an empty string; my fix proposes only to ignore null.

Repercussions of this, unknown. But seems to me to be correct, at least logically.

**Comment by cassidydotdk** [comment]
![checkbox funky](https://cloud.githubusercontent.com/assets/8483909/15878659/131745b8-2d1d-11e6-99cc-56ec421052c0.gif)

**Comment by stefansluijter** [comment]
We seem to have the same issue with our environment(s).
Contact me on Slack if you need any assistance on this issue.

**Comment by markgibbons25** [comment]
Would be good to get this one fixed, it's causing me headaches.

**Comment by kamsar** [comment]
I tested @cassidydotdk 's fix and it seems to work fine to me. This will be merged in the next version.

**Comment by cassidydotdk** [comment]
PR done.

The reason I didn't, wasn't actually so much because I was worried about the fix I proposed - I've been using that for a while and seen no real ill effects. It's more because of your comments in the code that follows:
`
				if (!string.IsNullOrEmpty(value))
				{
					fieldResults.Add(CreateFieldValue(field, value));
					continue;
				}

				// if the value was null or empty, we could still have a "significant empty value" - e.g.
				// a checkbox that is explicitly set to FALSE, when the standard value is TRUE
				// so we grab the value, allowing standard values, and if the standard value is not null or empty
				// we set the field value to an empty string explicitly
				var standardValue = field.GetValue(true, false);

				if(standardValue == null) continue;

				// given: the field value without standard values is null or empty (if above)
				// we verify: if the field is NOT a standard value (in which case we know the value is blank), AND the standard value is not empty
				// if so: we know the field has a significant empty value (its local value is blank and the standard value is NOT blank)
				if (!field.ContainsStandardValue && !string.IsNullOrEmpty(field.GetStandardValue()))
					fieldResults.Add(CreateFieldValue(field, string.Empty));

				// we check for empty or null standard values as a number of Sitecore default items have
				// explicit blank values set for fields whose standard value is also blank. Which is pretty pointless
				// to store in serialization as it's essentially a tautology.
`

Imagine for a minute, a non-native English speaker like myself even understand the word tautology... ;-) 

But from what I can tell; this code is doing nifty stuff with getting values from stdvalues item if the field was empty - and it addresses checkboxes as a potential problem.  My fix basically only works because it assumes; "empty value - if explicitly set on the item - is always significant". And if so, all the code following is actually redundant. Maybe. And this is what I was not so sure of - perhaps it should be gone as well? :-)

**Comment by cassidydotdk** [comment]
I'm also not sure if the fix will force people to need to reserialize.

**Comment by kamsar** [comment]
Released in 3.3.1
