### ISSUE TITLE
Auto Publish to multiple databases not working correctly

### ISSUE THREAD

**Issue by HenkMahieu** [kamsar/Unicorn#152]
I'm trying to set up autopublish but I'm having issues when publishing to multiple databases. I have the normal 'web' database and an additional pre-production database 'preprod'. As long as there is only one TargetDatabase in the config file everything works correctly. But if there are two and I try to execute the sync from the unicorn.aspx page I can see that the item is published to the first database but no items are published to the second database.

I'm using sitecore 8.1 update 2 and the unicorn package 3.2 from nuget. See my attached autopublish config file.

[Unicorn.AutoPublish.config.txt](https://github.com/kamsar/Unicorn/files/316862/Unicorn.AutoPublish.config.txt)

**Comment by HenkMahieu** [comment]
I think I have found the location of the issue and have tried to fix it. But to be honest, I have no deep experience with sitecore or with concurrent programming so I have no idea if this is a good or correct solution. I think it should work if you don't enable concurrency in unicorn. Any insight would be appreciated.

`
public class ManualPublishQueueHandler : PublishProcessor
{
	private static readonly ConcurrentQueue<ID> ManuallyAddedCandidates = new ConcurrentQueue<ID>();
	private static readonly ConcurrentQueue<ID> ManuallyAddedCandidatesSingleDatabase = new ConcurrentQueue<ID>();

	public static void AddItemToPublish(Guid itemId)
	{
		ManuallyAddedCandidates.Enqueue(new ID(itemId));
	}

	public static bool HasItemsToPublish => ManuallyAddedCandidates.Count > 0;

	public static bool PublishQueuedItems(Item triggerItem, Database[] targets, IProgressStatus progress = null)
	{
		if (ManuallyAddedCandidates.Count == 0) return false;

		foreach (var database in targets)
		{
			progress?.ReportStatus("> Publishing {0} synced item{2} in queue to {1}", MessageType.Debug, ManuallyAddedCandidates.Count, database.Name, ManuallyAddedCandidates.Count == 1 ? string.Empty : "s");

			var candidates = ManuallyAddedCandidates.ToArray();
			foreach (var candidate in candidates)
			{
				ManuallyAddedCandidatesSingleDatabase.Enqueue(candidate);
			}

			var publishOptions = new PublishOptions(triggerItem.Database, database, PublishMode.SingleItem, triggerItem.Language, DateTime.UtcNow) { RootItem = triggerItem, CompareRevisions = false, RepublishAll = true };

			var result = new Publisher(publishOptions, triggerItem.Languages).PublishWithResult();

			progress?.ReportStatus("> Published synced items to {0} (New: {1}, Updated: {2}, Deleted: {3} Skipped: {4})", MessageType.Debug, database.Name, result.Statistics.Created, result.Statistics.Updated, result.Statistics.Deleted, result.Statistics.Skipped);
		}

		return true;
	}

	public override void Process(PublishContext context)
	{
		var candidates = new List<PublishingCandidate>();

		ID candidate;
		do
		{
			if (!ManuallyAddedCandidatesSingleDatabase.TryDequeue(out candidate)) break;

			candidates.Add(new PublishingCandidate(candidate, context.PublishOptions));
		} while (candidate != (ID)null);

		context.Queue.Add(candidates);
	}
}
`

**Comment by kamsar** [comment]
Thank you for taking the time to diagnose. I'll try and get this merged up soon :)

**Comment by kamsar** [comment]
This will be fixed in the next version. Thanks for your issue report :)

**Comment by kamsar** [comment]
Released in 3.3.1
