### ISSUE TITLE
Error when configuration has a rolePredicate node but no predicate node

### ISSUE THREAD

**Issue by HarroSchmidt** [kamsar/Unicorn#156]
I created a configuration with only a rolePredicate with includes in it.
When I open the Unicorn dasboard it gives me the error "Invalid type null for Unicorn config node 'predicate', attribute 'type'" with the following stacktrace:

`[InvalidOperationException: Invalid type null for Unicorn config node 'predicate', attribute 'type']
   Unicorn.Configuration.XmlConfigurationProvider.GetConfigType(XmlElement configuration, XmlElement defaults, String elementName) +622
   Unicorn.Configuration.XmlConfigurationProvider.RegisterExpectedConfigType(XmlElement configuration, XmlElement defaults, String elementName, IConfiguration registry) +123
   Unicorn.Configuration.XmlConfigurationProvider.LoadConfiguration(XmlElement configuration, XmlElement defaults) +1336
   Unicorn.Configuration.XmlConfigurationProvider.LoadConfigurations() +597
   Unicorn.Configuration.XmlConfigurationProvider.get_Configurations() +28
   Unicorn.Data.DataProvider.UnicornSqlServerDataProvider..ctor(String connectionString) +64`

When I add a predicate node with includes the error is gone.

Using Unicorn  3.2.0

**Comment by kamsar** [comment]
See https://github.com/kamsar/Unicorn/blob/master/src/Unicorn.Roles/Standard%20Config%20Files/Unicorn.Configs.Default.Roles.config.example#L29

**Comment by HarroSchmidt** [comment]
Overlooked that. Thanks for pointing out.

**Comment by predragpjanovic** [comment]
I am still getting error: Invalid type Unicorn.Roles.Predicates.EmptyPredicate, Unicorn.Roles for Unicorn config node 'predicate', attribute 'type'

Could you help?

**Comment by predragpjanovic** [comment]
I managed to install it correctly. But i am little confused. When i create role there is no serialization file for that. I only getting serialization yaml files if i change security access rights. So i need to manually create this role on separate instance, do sync, and i will get restrictions. But i would like that when i do sync get this role automatically created. Is this possible?

**Comment by predragpjanovic** [comment]
I fixed it all :)
