### ISSUE TITLE
Extra slash added when escaping from webroot using ~\

### ISSUE THREAD

**Issue by TAllen** [kamsar/Unicorn#157]
Trying to config unicorn to place it's serialization folder, for example "~\App_Data\$(configurationName)" results in double slashes after the web root, i.e. "C:\inetpub\wwwroot\TEST\Website\\\\App_Data\TestWebsite".

**Comment by kamsar** [comment]
Ref: https://github.com/kamsar/Rainbow/commit/aa61a504055c0db28956395d60a893d590610717

This will be fixed in the next version

**Comment by kamsar** [comment]
Released in 3.3.1
