### ISSUE TITLE
Explicitly defined field values equalling standard values are not set

### ISSUE THREAD

**Issue by kamsar** [kamsar/Unicorn#162]
Reproduction:
- Make a test template with a text field
- Create standard values, set to 'foo'
- Create test item, set test field to 'bar', serialize it. The 'test field = bar' will be part of the item file.
- Change the standard value to 'bar'
- Saving the serialized item file, delete the test item from Sitecore
- Replace the item file and run a sync to add, then a sync to see the problem

Now for all future syncs, the item comparer will flag 'source = ', 'serialized = bar', but the deserializer will not set the value because it equals the standard value.

If a specific value exists in serialized, it should ALWAYS be set and override a standard value that happens to equal it. If the intent was to use the standard value, the item should not specify the field value.

**Comment by kamsar** [comment]
This will be fixed in the next release.

**Comment by cassidydotdk** [comment]
Sitecore doesn't do this either. If you enter a value in a field that is the exact same as Standard Values, the UI keeps displaying [standard value]. I usually add a space to whatever I'm inputting to make it stick, then remove the space and save again.

**Comment by kamsar** [comment]
Released in 3.3.1
