### ISSUE TITLE
Wildcard and implicit dependencies

### ISSUE THREAD

**Issue by kamsar** [kamsar/Unicorn#165]
The dependency system is receiving an upgrade.

## Wildcard dependencies

You can now use wildcards in your explicit configuration dependencies, e.g.

```
<configuration name="Monkey" dependencies="Foundation.*,Project.*">
...
</configuration>
```

## Implicit dependencies

These were proposed a long time ago by @Eldblom but the implementation had no tests and was a bit too buggy to ship. I've remedied that for the next release.

So what's an implicit dependency? Suppose:

Config `A` includes `/sitecore`
Config `B` includes `/sitecore/content`

Thus with implicit dependency `B` _automatically_ depends on `A` because a path included in `B` is a descendant of a path included in `A`.

Don't want an implicit dependency? Use `ignoredImplicitDependencies="Config1,Config.*"` on the configuration element.

Most of the time this will take care of your dependency needs without any interaction at all :)

**Comment by kamsar** [comment]
Released in 3.3.1

**Comment by wene37** [comment]
I tried to add wildcard dependency on an abstract base configuration (e.g.  `<configuration name="Base.Feature" abstract="true" extends="Base" dependencies="Foundation.*"></configuration>`).
Unfortunately this did not work. Is this by design, not implemented or a bug?

**Comment by cassidydotdk** [comment]
What error message did you receive @wene37. And what version did you use?

**Comment by wene37** [comment]
There was no error message. It only did ignore it. In the "Show Config" dialog of the configurations where no explicit dependencies listed (only implicit).
I'm using version 4.0.4.

**Comment by cassidydotdk** [comment]
Your configuration is being ignored because of `abstract="true"`. If you remove that, you will find that wildcarding (or otherwise) your `dependencies` will work as expected.

**Comment by wene37** [comment]
I can't remove `abstract="true"`, as those are base configurations which should not be synced. If I remove the abstract property, those are appearing in the sync as well.
Even if I remove the abstract property (for testing only), the real configurations, which extends the base configuration, do not get the dependency of the base configuration at all. So I believe the dependency attribute is just not designed to be declared in a base configuration.
