### ISSUE TITLE
Removing fields, or changing field types (versioned/shared) on template does not trigger content reserialize

### ISSUE THREAD

**Issue by thesoftwarejedi** [kamsar/Unicorn#171]
When deleting a field, old content will begin causing warnings when syncing.  No big deal.  When changing between shared/versioned, a hard error occurs during sync.  An error that's extremely difficult to debug!!

**Comment by blipson89** [comment]
@thesoftwarejedi slack history from the Sitecore Chat team doesn't get preserved. I've attached a screenshot of the conversation, as well as the 
[stacktrace](https://github.com/kamsar/Unicorn/files/468255/stacktrace.txt) snipped you posted, just in case.


![screenshot of the conversation](https://cloud.githubusercontent.com/assets/4602966/18450856/b862228c-7902-11e6-99cc-921f4b1bf3bf.png)

**Comment by kamsar** [comment]
Thanks Ben

**Comment by thesoftwarejedi** [comment]
After getting the error AGAIN, the title of this issue is not the root cause.  The error received is unrelated.  However, the propagation of changes in templates out to the content is still an issue unless a re-serialize is done.  This is consistent with pretty much all areas of trans sync so I feel this issue should be closed, and perhaps another brought forward to address propagating template changes to content.

**Comment by kamsar** [comment]
@thesoftwarejedi I forget did you mention you had found the actual error cause on Slack?

**Comment by kamsar** [comment]
Closing from inactivity presumed resolved

**Comment by DiegoSSJ** [comment]
Seems still relevant to me. Changing from not shared to shared on a field doesn't trigger any changes in serialized item what i can see.

**Comment by DiegoSSJ** [comment]
Workraound was to go to the field item and check 'shared' and save, then the item is serialized. And go back to the template's builder and do a save, so it updates from that. 
So this is more specific to the template builder.
