### ISSUE TITLE
Automated tool authentication method error for 3.1.7

### ISSUE THREAD

**Issue by AbhishekKumar26** [kamsar/Unicorn#172]
Hi All,

I am using Unicorn 3.1.7 and getting the attached issue.

Was not able to find anything in logs. Thanks in advance.
![capture](https://cloud.githubusercontent.com/assets/19407265/18508964/0ea5861a-7a94-11e6-9c5d-0bb553e4cb21.PNG)

**Comment by kamsar** [comment]
Your shared secrets don't match

**Comment by AbhishekKumar26** [comment]
I checked it from Unicorn.UI.config under IIS. Error has changed.
I am attaching the log. It was quite large.
[Log.txt](https://github.com/kamsar/Unicorn/files/474020/Log.txt)

**Comment by AbhishekKumar26** [comment]
After iterating through multiple projects of this solution, it gave the same error:

**_At F:\Saturn\trunk\Saturn\scripts\Unicorn\Unicorn.psm1:43
char:12
+     $result = Invoke-WebRequest -Uri $url -Headers @{ "X-MC-MAC" = $signature; "X-M ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand_**

**Comment by kamsar** [comment]
The second log you posted appears to be succeeding, including the secret negotiation, but throwing an exception for some reason. What version of Unicorn is this? The PowerShell API was introduced in 3.1.

**Comment by AbhishekKumar26** [comment]
The version of Unicorn is 3.1.7

**Comment by kamsar** [comment]
I would suggest looking at Habitat which is working example of the remote API. I believe they are using 3.1.7 as well last I knew. See this general area (they invoke it from Gulp) https://github.com/Sitecore/Habitat/tree/master/scripts
