### ISSUE TITLE
Race condition with multi-threaded sync

### ISSUE THREAD

**Issue by wolfeno** [kamsar/Unicorn#183]
I have configuration which includes about 4000 content items and some users with following configuration:

` <syncConfiguration updateLinkDatabase="true" updateSearchIndex="true" maxConcurrency="16" type="Unicorn.Loader.DefaultSyncConfiguration, Unicorn" singleInstance="true" />`

Running a synchronization with maxConcurrency=16  results in NullReferenceException

`ERROR: Object reference not set to an instance of an object. (System.NullReferenceException)
at Unicorn.Pipelines.UnicornSyncComplete.AddSyncedItemsToPublishQueue.Process(UnicornSyncCompletePipelineArgs args)`

Collection _entries [here](https://github.com/kamsar/Unicorn/blob/master/src/Unicorn/Pipelines/UnicornSyncComplete/DefaultSyncCompleteDataCollector.cs#L22) contains null items due to race condition with queue operations. 
Replacing Queue with ConcurrentQueue resolves a problem.

Sitecore 8.1 Update 2; Unicorn 3.3 RC3 - RC9

**Comment by kamsar** [comment]
Fixed in 3.3.1-RC01. Thanks for the report :)

**Comment by wolfeno** [comment]
Verified as fixed in 3.3.1-RC01
