### ISSUE TITLE
targetDataStore Question

### ISSUE THREAD

**Issue by roganflitton** [kamsar/Unicorn#185]
Hi there,
I followed the following steps when creating a Sitecore 8.2 MVC solution: [https://www.akshaysura.com/2016/06/29/tihidi-setup-a-visual-studio-2015-sitecore-8-x-mvc-solution/]

Basically my source code is separate from my local Sitecore instance. I publish my source code to my local Sitecore instance, but the problem I have is Unicorn runs on my local Sitecore instance and the Sitecore items are serialized to the App_Data folder of my local sitecore instance, but I need it to rather serialize to my source code as that is what I'm pushing to our GIT repo. Bare in mind that there is a team of us working on this so I want the process to be seamless.

Any ideas?

**Comment by kamsar** [comment]
Check out how Habitat handles it. It's solution (using variables to point
to out of webroot serialized files) works quite well. Start with the items
config of almost any feature module.
