### ISSUE TITLE
Media Item "Detach" not working

### ISSUE THREAD

**Issue by thesoftwarejedi** [kamsar/Unicorn#187]
Latest version of Unicorn/Rainbow, unable to press "detach" on the Media of a Media Item. 

Because new value is null, guid parsing fails [here](https://github.com/kamsar/Unicorn/blob/master/src/Unicorn/Data/DataProvider/FieldChangeParser.cs#L51).

[FormatException: Unrecognized Guid format.]
   System.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException) +4608068
   System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult& result) +138
   System.Guid.Parse(String input) +197
   Unicorn.Data.DataProvider.FieldChangeParser.ParseFieldChanges(IEnumerable`1 applicableFieldChanges, IEnumerable`1 baseFieldValues, String databaseName) +834
   Rainbow.Model.ProxyItem..ctor(IItemData itemToProxy) +297
   Rainbow.Storage.SerializationFileSystemTree.WriteItem(IItemData item, String path) +147
   Rainbow.Storage.SerializationFileSystemTree.Save(IItemData item) +75
   Unicorn.Data.DataProvider.UnicornDataProvider.SaveItem(ItemDefinition itemDefinition, ItemChanges changes, CallContext context) +930
   Unicorn.Data.DataProvider.UnicornSqlServerDataProvider.SaveItem(ItemDefinition itemDefinition, ItemChanges changes, CallContext context) +194
   Sitecore.Data.DataProviders.DataProvider.SaveItem(ItemDefinition item, ItemChanges changes, CallContext context, DataProviderCollection providers) +138

**Comment by kamsar** [comment]
This is fixed in Unicorn 3.3.2.
