### ISSUE TITLE
Feature: configurable minimum password length for UserLoader

### ISSUE THREAD

**Issue by Eldblom** [kamsar/Unicorn#190]
I would like to be able to specify the minimum password length for the UserLoader. For demo scenarios we would like our users to have the default Sitecore password - which is not possible with the current scenario.

For example:

`<userLoader type="Unicorn.Users.Loader.UserLoader, Unicorn.Users" singleInstance="true" minimumPasswordLength="8"/>`

**Comment by kamsar** [comment]
I'd be willing to merge a PR for this, as long as the default settings remain secure.

**Comment by kamsar** [comment]
This is now part of #191 (next time one PR per issue please @Eldblom 😀 )

**Comment by kamsar** [comment]
This will be in 4.0.
