### ISSUE TITLE
Feature request: list invalid item paths during initial setup

### ISSUE THREAD

**Issue by JamesSkemp** [kamsar/Unicorn#194]
**Do you want to request a *feature* or report a *bug*?**
Feature request.

**What is the current behavior?**
The following message displays if you setup Unicorn pointing to items that don't exist in Sitecore:

> Cannot perform initial serialization because the predicate configuration is including item paths which do not exist in the database.

What I don't see is information on what items don't exist.

**If the current behavior is a bug, please provide the steps to reproduce.**
n/a

**What is the expected behavior?**
It would be great if either in the Serialization Preset Predicate section or under the Initial Setup section it listed the invalid item paths.

**Please mention your Sitecore version and Unicorn version.**
Sitecore 8.1.160519, Unicorn 3.3.2

**Comment by kamsar** [comment]
How's this:
![image](https://cloud.githubusercontent.com/assets/103677/22236671/f4bf8720-e1bb-11e6-867f-716888595d39.png)

Will be in the next version. Thanks for asking, good idea :)

**Comment by JamesSkemp** [comment]
Looks great; thanks!

**Comment by kamsar** [comment]
This will be in 4.0.
