### ISSUE TITLE
Using transparent sync on CD

### ISSUE THREAD

**Issue by cpalm** [kamsar/Unicorn#199]
**First off, I love Unicorn**

This is just a question. And to keep it simple, let's say it is only about /sitecore/templates/my-templates

I would like to use transparent sync on the CD server when I deploy, this way I don't need to do a publish and rollback is simple.

On dev I will have
`<include database="master" path="/sitecore/templates/my-templates" name="master-my-templates" />`

But since the CD i running on web database, how can I use the unicorn files on CD, what is best practice.

**Solution 1.**
I could also include:
<include database="web" path="/sitecore/templates/my-templates" name="web-my-templates" />
And then remember to publish from master to web before I commit unicorn files.
This could/will lead to human error :-(

**Solution 2.**
Copy the Master unicorn files to CD and then config transform the unicorn config, where I will replace the database="master" to database="web"
But is kind of smells like a hack

What is best practice? could use some advice

Kind regards
Christian

**Comment by kamsar** [comment]
This setup would theoretically work, and now that transparent sync has been around for a while I think it could be ok. You're experimenting in new territory here - not to say that it won't work, but that there are no established practices around the technique. It is also likely that Transparent Sync performance is not quite at the same level as SQL based templates (make sure to turn data cache on), and you'll be defeating publishing for templates which might make the link database go out of date in regards to templates.

You'd probably, as you said, wish to transform the config to change the database to web on CD. You'd also want to duplicate the configs on CE and have them point at both master and web.

**Comment by mjarosch** [comment]
@cpalm Did you ever go forward with this? If so, what was your experience with it? Are you aware of anyone who has done this?

@kamsar Is this still experimental territory? Are you aware of anyone who has done this? Blog posts about it (my Google fu is failing here)?

I have been thinking about doing something similar to this for templates, renderings and other non-content items to get the benefits cpalm mentions.

Is the link database an order of operations for deployment? If the website was running when the sync of items happened, would the link database get updated?

Are there other things to worry about? Like a template gets deleted for an item that was deleted in master, but the delete didn't get published to web?
