### ISSUE TITLE
EXM behaves incorrectly/crashes when transparent sync is used and EXM root is serialized

### ISSUE THREAD

**Issue by ivanbuzyka** [kamsar/Unicorn#200]
Reproducing scenario:

1. Install Sitecore 8.2 + EXM 3.4 (configure local MTA for example)
2. Create few messages in the EXM root.
3. Install Unicorn (I used Nuget package and publishing from VS) and configure Unicorn project to include EXM root: e.g. <include name="exm" database="master" path="/sitecore/content/Email Campaign" />
4. Update  enableTransparentSync to "true"
5. Open EXM SPEAK app and create new message from One-Column or Two-column message template edit that message.

Problems: 
1. "Message" tab in SPEAK app is never accessible, SPEAK app hangs
2. Sometimes W3wp process crashes

Note: I don't see anything in Sitecore log files.
Note 2: in case enableTransparentSync="false" EXM works as expected.

**Comment by kamsar** [comment]
I would guess that EXM may be using Fast Query. Transparent Sync does not support Fast Query.

For applications that require Fast Query, you must disable Transparent Sync.

**Comment by kamsar** [comment]
Note that #196 adds a log warning when fast: is used and transparent sync is on.
