### ISSUE TITLE
Bug: Configurations which include the same root path delete each other's .yaml files on reserialization

### ISSUE THREAD

**Issue by vlaloggia** [kamsar/Unicorn#201]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Given the existence of the two attached Unicorn.config files, reserializing the Parent Configuration deletes all the Dependent Configuration items, and vice versa.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Copy Unicorn.Dependent.config and Unicorn.Parent.config to /Website/App_Config/Include/Unicorn
2. Open the Unicorn.aspx page and perform a Reserialization of "Parent Configuration"
3. Examine the contents of C:/MyDirectory/Unicorn to see a serialization of the /sitecore/Media Library/Images folder
4. Return to Unicorn.aspx and perform a Reserialization of "Dependent Configuration"
5. Examine the contents of C:/MyDirectory/Unicorn to see that the serialization of the /sitecore/Media Library/Images folder has been deleted, but now a serialization of /sitecore/Media Library/Experience Explorer exists.

**What is the expected behavior?**
When serializing a configuration, only that configuration's items should be deleted and recreated - not all items.

**Please mention your Sitecore version and Unicorn version.**
Sitecore.NET 8.1 (rev. 160519)
Unicorn 3.3.2

[Unicorn.zip](https://github.com/kamsar/Unicorn/files/711929/Unicorn.zip)

Thank you,
vic

**Comment by kamsar** [comment]
Ok I see what you're doing here. Both configurations are set to identical roots. This is essentially telling them to overwrite each other - each configuration must have its own separate physical root.

As the docs in the stock `Unicorn.config` say:

```
<!--
		The target data store is where we write serialized items to.

		Note the target data store's rootPath can be any of:
		Absolute filesystem path, e.g. c:\foo\bar
		Web-root-relative path, e.g. ~/data/serialization or ~/../out-of-root-serialization
		Data-folder-relative path, e.g. $(dataFolder)\serializedItems

		DO NOT SHARE A ROOT PATH BETWEEN CONFIGURATIONS (at least if you're using SFS).
		They can clobber each other's folders. You may inject the name of the current
		configuration as a variable with $(configurationName).

		The data cache uses a memory cache to store serialized items read from disk. It
		is recommended if using transparent syncing for performance. It's not really
		needed otherwise.
	-->
<targetDataStore physicalRootPath="$(dataFolder)\Unicorn\$(configurationName)" useDataCache="false" type="Rainbow.Storage.SerializationFileSystemDataStore, Rainbow" singleInstance="true"/>
```

**Comment by vlaloggia** [comment]
Thank you Kam.

However, what's unclear to me is that the targetDataStore is part of the <defaults> element, not the <configurations> element. Might I ask how I would define a unique targetDataStore for the dependent configuration? Is it as simple as creating a complete Unicorn.Dependent.confg?

**Comment by kamsar** [comment]
Any node in defaults in unicorn.config can be overridden in an individual
config by copying and modifying the element to be changed.

Think of it as each config being an IoC container but it contains defaults
unless you change them.

**Comment by vlaloggia** [comment]
Understood, thank you.

Unfortunately, in my case, I need to merge two disparate Unicorn physical stores. So far, availing myself of Sitecore's .config patching is working out well.

Thank you for your time and attention sir.

vic
