### ISSUE TITLE
Reevaluate Threading Patterns

### ISSUE THREAD

**Issue by kamsar** [kamsar/Unicorn#202]
When Unicorn was architected, it was optimized for few larger configurations to sync. This is why the multithreaded model was made to act within a configuration.

Fast forward to today, and most architectures (e.g. Helix) are using many small configurations instead.

Investigate moving the threading model so that configurations are always single threaded, and when syncing multiple configurations maybe we can add a flag to allow a configuration to go in parallel with other configs.

I suspect in some cases removing multithreading within a config will also greatly improve spin-up time for the sync to go forward.

**Comment by kamsar** [comment]
Done. Multithreading will be removed in the next release as it was indeed adding little.

**Comment by thesoftwarejedi** [comment]
@kamsar Did this ever get out in a release?  I'm pretty sure this is causing random initial sync issues in our large Helix solutions.  Errors like ParentNotFoundException but the parent is very clearly there on disk, and all IDs correct.  A half dozen sync attempts and it finally works.

**Comment by kamsar** [comment]
Threading is set to one by default in almost all u3 releases. U4 removes
threading support.

**Comment by kamsar** [comment]
This will be in 4.0.
