### ISSUE TITLE
Reserializing is extremely slow after upgrading to 3.3.2

### ISSUE THREAD

**Issue by demisx** [kamsar/Unicorn#205]
Hi Kam,

We've just upgraded to the latest Unicorn 3.3.2 in two environments (local and staging) and tried to reserialize one site. It was blazing fast in local, but on staging it's taking forever (like 1 second per item). I see the following written to the Sitecore log per each item:

```
...
2017-01-26 01:00:23:08 INFO  Serialized item C:\Inetpub\wwwroot\sc\Website\data\Unicorn\Site.com\Templates\site-com\Components\ScheduleSection.yml deleted, reloading caches.
2017-01-26 01:00:23:08 WARN  All caches have been cleared. This can decrease performance considerably.
2017-01-26 01:00:26:16 INFO  Serialized item C:\Inetpub\wwwroot\sc\Website\data\Unicorn\Site.com\Templates\site-com\Components\ScheduleTextTab\Data\TextLabel.yml deleted, reloading caches.
...
```

Any idea what could be causing this? Should I expect that the second pass will much faster? We had to reinstall .NET4.5.2 on staging and re-target the IIS 7 application pool to v4.0 again. Not sure if this could be causing it.

**Comment by kamsar** [comment]
Make sure that you have `singleInstance="true"` on your data stores' registrations, both source and target.

**Comment by demisx** [comment]
The second and third pass went through much faster as expected. I guess somehow the cache had to be rebuilt. Thank you so much for your blazing support as always. One awesome product you've got here.

**Comment by demisx** [comment]
One thing I've noticed with the new 3.3.2 version on one of the larger sites that often syncing quits with OutOfMemory exception now. Not sure if this is an issue or not:

```
Tree failed to load: master:/sitecore/media library/client/full/client-com (da25d49f-7652-4508-8154-ea22eca0c10b) (the error may be on a child of this item, see the details below)
C:\Inetpub\wwwroot\client\Website\data\Unicorn\client.com\MediaLibrary\client-com.yml
> SfsReadException: Error while reading SFS item C:\Inetpub\wwwroot\client\Website\data\Unicorn\client.com\MediaLibrary\client-com\content\ppts\2016-efm-overview-mcrc-treatme.yml
> YamlFormatException: Error parsing YAML C:\Inetpub\wwwroot\client\Website\data\Unicorn\client.com\MediaLibrary\client-com\content\ppts\2016-efm-overview-mcrc-treatme.yml
> OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
```

**Comment by kamsar** [comment]
@demisx do you have datacache enabled?

**Comment by demisx** [comment]
@kamsar Not sure. Where would I check?

**Comment by kamsar** [comment]
Target data store

**Comment by demisx** [comment]
OK. I see this in `Unicorn.config`:

```xml
<targetDataStore physicalRootPath="$(dataFolder)\Unicorn\$(configurationName)" useDataCache="false" type="Rainbow.Storage.SerializationFileSystemDataStore, Rainbow" singleInstance="true"/>
```

Should I try setting `useDataCache="true"`?

**Comment by kamsar** [comment]
no that'd make it use more RAM :grin: 

if you're handy with a memory profiler I'd love to see if we can figure out how to lower the memory needed; I'll probably do some profiling of my own as well but I don't necessarily have the volume of media it sounds like you do

**Comment by demisx** [comment]
Any way to set the `useDataCache="false"` just for the site that experiences out of memory exception if that helps?  Maybe inside `Unicorn.Configs.[SiteName].conig` file?

I haven't used memory profiler on Windows platform yet, but I am sure I can manage it. Any recommendation on which profiler to use?

**Comment by kamsar** [comment]
It sounds like it was already false.

I use dotMemory, but there are others like ANTS as well.
