### ISSUE TITLE
Issue with Unicorn 3.1.7 on Sitecore 8.1.160519

### ISSUE THREAD

**Issue by alokce** [kamsar/Unicorn#207]
Hi Team,

The '05-Sync-Unicorn'... function is not working. It is keep displaying Starting '05-Sync-Unicorn'... for several hours. Please let me know if I am missing any thing.

Thanks,
Alok Kumar

**Comment by kamsar** [comment]
You may have better luck with this issue over on the Habitat repository, or on [Sitecore StackExchange](http://sitecore.stackexchange.com/). Habitat has their own extensions, including the gulp task, which invoke Unicorn.

**Comment by alokce** [comment]
Hi,

I am using the Habitat repository and when run the default task in the Visual Studio Task Runner Explorer it get stuck at task '05-Sync-Unicorn'. It always shows Starting '05-Sync-Unicorn' and never completed. Where do you log the error / exception so that I can check if any error occurred during this task. All other tasks are completed successfully.

Thanks,
Alok...

**Comment by kamsar** [comment]
You'll want to ask Habitat related questions over on the [Habitat repository](https://github.com/Sitecore/Habitat). I just work on Unicorn in my spare time, and I'm not a Habitat expert.
