### ISSUE TITLE
Add dependency graph tool via SPE script

### ISSUE THREAD

**Issue by michaellwest** [kamsar/Unicorn#212]
https://alan-null.github.io/2017/01/unicorn-dependency-graph

@alan-null

**Comment by kamsar** [comment]
While this is a totally cool tool, it's also pretty tightly tied with dependencies that I think are inappropriate to take into the Unicorn core (SPE, yuml.me). I'm inclined to not add it, but to link to it as a neat tool from the docs or the control panel. What do you think?
