### ISSUE TITLE
$(configurationName) not replaced before checking for illegal characters 

### ISSUE THREAD

**Issue by niles11** [kamsar/Unicorn#214]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Using the same configuration as with Unicorn 3, I get the following exception in Application_Start():

_Illegal character $ in tree root physical path D:\Company_Web\Sitecore\serialization\$(configurationName)\T_Company. If you're using Unicorn, you may need to specify a 'name' attribute on your include to make the path a valid name._

**If the current behavior is a bug, please provide the steps to reproduce.**
Upgrade from Unicorn 3 to Unicorn 4 while keeping existing configuration files that worked under Unicorn 3. Nothing else changed except for updating to Unicorn 4 with Nuget package manager console.

**What is the expected behavior?**
I expect the $(configurionName) placeholder to be replaced by the actual configuration name. This way, it should no longer contain a dollar character when checking for illegal characters and thus it should no longer throw an exception.

**Please mention your Sitecore version and Unicorn version.**
Sitecore 8.1 rev. 151207 and Unicorn version 4.0.0-Pre04

**Comment by kamsar** [comment]
Fixed in 4.0.0-pre05

**Comment by kamsar** [comment]
This will be in 4.0.
