### ISSUE TITLE
Media Lib deserialze taking longer time 

### ISSUE THREAD

**Issue by ramnkl16** [kamsar/Unicorn#216]
I'm working one of the migration project from  7.2 140526 to 7.2 160123, Started using unicorn for content move from lower ver to 7.2 16.   Serialization is done in few mins for media lib about 565 mb size. while sync with new database content node items are done fast. But media lib sync is taking about 10 mins per file
Both the database are reside on the same data
Below is the console message
[U] master:/sitecore/media library/Dewalt/Images/Safety_Recall/2005RepairProgramfor1373nailerrepair (f3ec0ba1-1a81-467d-9381-7064da72dc1c)
> Template: Serialized 'Image', Source 'Image'
* [T] from Image to Image
[U] master:/sitecore/media library/Dewalt/Images/Safety_Recall/2007DEWALTDC305recipsaw (b5cb48fe-a12a-4041-b529-d1c20d41b754)
> Template: Serialized 'Image', Source 'Image'
* [T] from Image to Image

I have also attached the item the yaml and log files.
Sitecore version 7.2. 160123 and Unicorn version 4 
[2005RepairProgramfor1373nailer.zip](https://github.com/kamsar/Unicorn/files/888148/2005RepairProgramfor1373nailer.zip)

Note: I have setup separate sitecore instance for deserialize. Another instance is running using the same database for website content delivery.

**Comment by kamsar** [comment]
It appears that the template ID of the serialized item, and the item in Sitecore do not match. This is causing it to deserialize the blob each time, which is slow. Verify your IDs match between the items.

You mentioned using Unicorn 4 - which version? Some of the earlier prerelease versions had some silly bugs (the current versions are being used in a production site). Does the same issue happen with 3.3.x?
