### ISSUE TITLE
Unicorn aspx page notfound exception

### ISSUE THREAD

**Issue by dbalosetti** [kamsar/Unicorn#218]
Hi dear,
i've installed from nuget unicorn 3.3.2 (we are using Sitecore.NET 8.2 (rev. 160729)) but i've a strange behaviour, if i tried to call /unicorn.aspx i get a 302 redirecto to notfound.aspx?item=%2funicorn&user=sitecore%5cXXXX&site=website.
We have a quite big url rewrite file but i've disable it. We are variuous site config in SiteDefinition.config and we use virtualFolder for each one.
I know that is not easy to understang what's wrong but any help could be appreciated.

Best regards,
Davide

**Comment by kamsar** [comment]
I'd try process of elimination. Try disabling sitedefinition.config. Make
sure you reset iis after disabling rewrites (it gets greedy). Make sure
debug compilation is enabled for local, and that /sitecore/admin/login.aspx
exists for remote login.

**Comment by dbalosetti** [comment]
Thanks kamsar for your fast reply..i've tried to disable sitedefinition.config, url rewrite and the other two points but it  still doesn't work..have you got any other suggestions?
Thanks in advance,
Davide

**Comment by kamsar** [comment]
The control panel is patched in using this code:

```<httpRequestBegin>
				<!--
					This pipeline handler shows the Unicorn control panel. You can customize the URL the control panel lives at by changing the activationUrl.
					The activationUrl must be a URL that the Sitecore pipeline won't ignore (e.g. .aspx, .ashx, etc)
				-->
				<processor patch:after="*[@type='Sitecore.Pipelines.HttpRequest.UserResolver, Sitecore.Kernel']" type="Unicorn.ControlPanel.UnicornControlPanelPipelineProcessor">
					<param desc="activationUrl">/unicorn.aspx</param>
				</processor>
			</httpRequestBegin>```

If you've altered or moved the `UserResolver` in the pipeline, the patch could apply at the wrong place and prevent activation of the control panel.

**Comment by dbalosetti** [comment]
Now it works! In fact we have altered UserResolver..
Thanks for your very appreciated help!

Davide
