### ISSUE TITLE
Unicorn revision for Publishing Service

### ISSUE THREAD

**Issue by michaellwest** [kamsar/Unicorn#220]
Message from @kamsar 
I was thinking about your revision issue last night and I suspect I might know what it is ... but I'm not entirely sure that Unicorn will force a new revision when it deserializes, which would be a bug and confuse publishing service no doubt

adding revision to your serialized items isn't a great solution either b/c you'll get a ton of fake changes to your serialized items

**Comment by kamsar** [comment]
We managed to replicate this as an apparent Sitecore bug, that smart publish is no longer publishing item renames. I was able to replicate the lack of publishing of renamed items with Unicorn disabled and on non-Unicorn controlled items.
