### ISSUE TITLE
Reserializing Synced Content Modifies Items

### ISSUE THREAD

**Issue by MrSnappingTurtle** [kamsar/Unicorn#223]
*bug*/*question*

Developer A and B have the same files in Unicorn (tracked by git). Both developers run a Unicorn sync to make sure they are in sync with what's in git. Afterwards both developers run a reserialize. Developer A's `git status` is clean, as expected. However, developer B's `git status` returns changes. 

Here are some examples:

* Many files being deleted:

    
 ```D "dotnet/core/website/data/Unicorn/SomeSiteCom/ProfessionalNephrologyTemplates/Nephrology/SomeSite-Professional Nephrolog/Content/Content.yml"
 D "dotnet/core/website/data/Unicorn/SomeSiteCom/ProfessionalNephrologyTemplates/Nephrology/SomeSite-Professional Nephrolog/Header.yml"
 D "dotnet/core/website/data/Unicorn/SomeSiteCom/ProfessionalNephrologyTemplates/Nephrology/SomeSite-Professional Nephrolog/Header/For Patients.yml"
 D "dotnet/core/website/data/Unicorn/SomeSiteCom/ProfessionalNephrologyTemplates/Nephrology/SomeSite-Professional Nephrolog/Header/Important Safety Information L.yml"
 D "dotnet/core/website/data/Unicorn/SomeSiteCom/ProfessionalNephrologyTemplates/Nephrology/SomeSite-Professional Nephrolog/Header/Indication.yml"
 D "dotnet/core/website/data/Unicorn/SomeSiteCom/ProfessionalNephrologyTemplates/Nephrology/SomeSite-Professional Nephrolog/Header/Prescribing Information and Me.yml"
 D "dotnet/core/website/data/Unicorn/SomeSiteCom/ProfessionalNephrologyTemplates/Nephrology/SomeSite-Professional Nephrolog/Prescribing Information Links.yml"
 D "dotnet/core/website/data/Unicorn/SomeSiteCom/ProfessionalNephrologyTemplates/Nephrology/SomeSite-Professional Nephrolog/Prescribing Information Links/Instructions for use.yml"
 D "dotnet/core/website/data/Unicorn/SomeSiteCom/ProfessionalNephrologyTemplates/Nephrology/SomeSite-Professional Nephrolog/Prescribing Information Links/Medication Guide.yml"

```

* Fields being added:

```
M dotnet/core/website/data/Unicorn/SomeSiteCom/Content/www-SomeSite-com/professional/oncology/declining-hb.yml

DB: master
+SharedFields:^M
+- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"^M
+  Hint: __Renderings^M
+  Type: layout^M
+  Value: ^M
```

~~Looking into the database, the deleted files are still present so they should have been reserialized.~~

Any suggestions as to what might be causing this?

Thanks!

**Comment by kamsar** [comment]
Possibly something to do with file permissions? Mismatching parent IDs or items that are not serialized that are altering how things are processed?

I have not seen this issue. You might try seeing what happens if you take a copy of Developer B's master database and reserialize using that - it would isolate the issue being something outside Unicorn on your local DB.

**Comment by MrSnappingTurtle** [comment]
@kamsar Thanks for the quick response. I'll keep the description updated as I learn more. I'll look into your suggestion. This isn't the highest priority on my list of issues so it might be a few days until I get to trying out the database copy. Thanks again.

**Comment by MrSnappingTurtle** [comment]
@kamsar I got back into looking at this and noticed something. It looks almost as if when I reserialize, the order in which the items were reserialized was changed. 

I have three items:

* SomeSite-Professional Nephrology Base `{733AAFEE-19FE-49E4-B70D-48EF1F9C4C0D}`
* SomeSite-Professional Nephrology 1 col `{6C3A2BA8-32A2-49CC-9431-8C9ECB2EA2EB}`
* SomeSite-Professional Nephrology 2 col `{1E90FFCD-676A-456E-B65B-0C347F6A7AC3}`

However, when initially serialized, their folder names were truncated and ended up having to be distinguished by id:

* `.../Nephrology/SomeSite-Professional Nephrolog`
* `.../Nephrology/SomeSite-Professional Nephrolog_1e90ffcd-676a-456e-b65b-0c347f6a7ac3`
* `.../Nephrology/SomeSite-Professional Nephrolog_6c3a2ba8-32a2-49cc-9431-8c9ecb2ea2eb`

I realized that when I reserialized and saw all the odd changes, they were actually the three aforementioned items "switching" folders. Here is the same directory post reserialization (notice the IDs are not different but rather "swapped"):

* `.../Nephrology/SomeSite-Professional Nephrolog`
* `.../Nephrology/SomeSite-Professional Nephrolog_1e90ffcd-676a-456e-b65b-0c347f6a7ac3`
* `.../Nephrology/SomeSite-Professional Nephrolog_733aafee-19fe-49e4-b70d-48ef1f9c4c0d`

However, this different "order"/folder "swap" only happens on my machine, not another developers. Is this something you've seen before? I'm going to follow your suggestion and try importing the other developer's same items next.

**Comment by MrSnappingTurtle** [comment]
I can confirm that importing another developer's package which contains the three items mentioned above has the same "swapping" result when reserializing post import.

**Comment by kamsar** [comment]
I suspect the order change is due to other factors, e.g. subitem ordering,
standard values, or other factors outside those specific items.

The items shortened names are guaranteed to be 'sticky' once created, but
reserialization is first in gets the ID-less name so it's not guaranteed to
keep the same hierarchy on reserialize in some cases.

**Comment by MrSnappingTurtle** [comment]
Just wanted to let you know, I had to rearrange many of the Sitecore items and reserialize as part of the project I was working on. This behavior stopped after doing that.
