### ISSUE TITLE
Question: Different itemname for the same item

### ISSUE THREAD

**Issue by Rclemens** [kamsar/Unicorn#225]
Hi there,

We're using Unicorn on a project with multiple developers.

**versions:** 
- Unicorn: v4 update 9
- Sitecore 8.2 update 2

What we're seeing is that for some developers Unicorn generates the same item with a different name. It looks like they have a different maxpathlength.

So we've changed the SerializationFolderPathMaxLength in the Sitecore.config and Rainbow.config to 90, but that didn't change anything.

The ideal situation would be that all dev machines produce the same itemname.

Do you have any suggestions?

**Comment by kamsar** [comment]
Can you provide some concrete examples?
