### ISSUE TITLE
Unable to serialise item into a IIS virtual folder 

### ISSUE THREAD

**Issue by howej** [kamsar/Unicorn#227]
I am using Sitecore 8.2 update 3 and the latest version of Unicorn.

In IIS, I have created a virtual folder inside Sitecore data folder which is pointing to somewhere.

For example, ~/data/unicorn_output, unicorn_output is a virtual folder.

When I was trying to serialise the items, no file was created under the virtual folder but in the data folder.

Any idea please advise.

Thanks

**Comment by kamsar** [comment]
Unicorn operates at a filesystem level, and is unaware of virtual mappings made in IIS. It would work if it was a symbolic link at the filesystem level.
