### ISSUE TITLE
[Question] Could not resolve type name: Unicorn.Configuration.XmlConfigurationProvider When Upgrading From 3.x to 4.

### ISSUE THREAD

**Issue by MrSnappingTurtle** [kamsar/Unicorn#229]
Hey, 

We were upgrading from 3.3.2 to 4. If I'm correct, this update only requires me to update the packages with the following command:

`Install-Package Unicorn.Core -Version 4.0.0-pre03 -Pre`

However, after running the install and attempting to access the control panel, I am presented with this:

![2017-06-01 15_49_35-could not resolve type name_ unicorn configuration xmlconfigurationprovider uni](https://cloud.githubusercontent.com/assets/8148243/26704113/f25fcf54-46e1-11e7-852d-b75083044bc3.png)

Is there something I'm missing? I can use my old configs, right? Thanks for your help!

Sitecore 7.5/Unicorn 3.3.2

**Comment by kamsar** [comment]
Sounds like the Unicorn.config didn't get updated; v4 uses some new config infrastructure to support the enhanced config stuff (https://kamsar.net/index.php/2017/02/Unicorn-4-Part-III-Configuration-Enhancements/)

**Comment by kamsar** [comment]
btw, you should install the latest prerelease by just adding `-Pre` with no version specified. There are some decent bug fixes since pre03.

**Comment by MrSnappingTurtle** [comment]
Thanks for the quick response as always! Turns out it wasn't generating configs because I was installing `Unicorn.Core` rather than just `Unicorn`. Also thanks for the version tip.
