### ISSUE TITLE
Bug: Custom condition uid wrong format

### ISSUE THREAD

**Issue by ricardoazeitona** [kamsar/Unicorn#230]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The uid of custom condition has wrong format, when trying to "Personalize" the rule in Final Layout inside Content Editor of Sitecore, it crash as uid not well fromatted.

**If the current behavior is a bug, please provide the steps to reproduce.**
It happened with custom rule set, all the custom rule set are generated wrong uid in conditions

>  <conditions>
>                   <or
>                     uid="82E63E4F66C14FAEA72FAFD8EE402A4C">
>                     <or
>                       uid="**600B4689E5CE477ABE13472382919E94**">
>                       <condition
>                         id="{35894966-8C1C-4D0B-888B-88BD1599D881}"
>                         uid="6F13174F5E694049A4AB28281940DCE8"
>                         except="true" />
>                       <condition
>                         id="{D69DE001-6126-438D-88D2-637082D7CA5A}"
>                         uid="97AB229A76DB424FA0D7C1CFE3ABAA2C"
>                         except="true" />
>                     </or>
>                     <condition
>                       id="{036A0990-9D1A-480F-850C-F36DDCAC223F}"
>                       uid="**DF38DD1BA08F46BBAE61D33EEF14C908**" />
>                   </or>
>                 </conditions>

**What is the expected behavior?**

**Please mention your Sitecore version and Unicorn version.**
Unicorn 3.3.2
Sitecore 8.1

**Comment by kamsar** [comment]
If I'm understanding this issue correctly, I think I can reproduce but it looks like it's a Sitecore bug. Here's what I did:

1. Grabbed an existing item in Content Editor
2. Added a rendering to it
3. Added a personalization state and set a sample personalization condition (`date > x`)
4. Inspected the resultant YAML file

I see this XML in the YAML - I presume you're talking about the `uid` attribute on the `condition` nodes (e.g. `uid="D2CEC0CD1CB540AD944FD1F86DD0D9B4"`):

```xml
<r xmlns:p="p" xmlns:s="s"
  p:p="1">
  <d
    id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
    <r
      uid="{BB7BF42B-6467-4928-B774-5955AC0A00ED}"
      s:id="{690A52CA-C0D6-4F2C-91F6-71D96D5FB511}"
      s:ph="fop">
      <rls>
        <ruleset>
          <rule
            uid="{A13C2B40-7692-499F-B464-88F4C75F5D82}"
            s:name="sdfsdf">
            <conditions>
              <condition
                uid="D2CEC0CD1CB540AD944FD1F86DD0D9B4"
                s:id="{8A9B001F-FB59-4F0F-B3F3-C6C5360ED451}"
                s:Now="20170608T045100Z" />
            </conditions>
          </rule>
          <rule
            uid="{00000000-0000-0000-0000-000000000000}"
            s:name="Default">
            <conditions>
              <condition
                uid="3BB819BA28C840F3B0CBD8145965F714"
                s:id="{4888ABBB-F17D-4485-B14B-842413F88732}" />
            </conditions>
            <actions />
          </rule>
        </ruleset>
      </rls>
    </r>
  </d>
</r>
```

Unicorn just formats the XML prettily, it doesn't change the actual values. So I checked the `__Final layout` field, and it seems to have stored the same values, just not pretty printed:

```xml
<r xmlns:p="p" xmlns:s="s" p:p="1"><d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"><r uid="{BB7BF42B-6467-4928-B774-5955AC0A00ED}" s:id="{690A52CA-C0D6-4F2C-91F6-71D96D5FB511}" s:ph="fop"><rls><ruleset><rule uid="{A13C2B40-7692-499F-B464-88F4C75F5D82}" s:name="sdfsdf"><conditions><condition uid="D2CEC0CD1CB540AD944FD1F86DD0D9B4" s:id="{8A9B001F-FB59-4F0F-B3F3-C6C5360ED451}" s:Now="20170608T045100Z" /></conditions></rule><rule uid="{00000000-0000-0000-0000-000000000000}" s:name="Default"><conditions><condition uid="3BB819BA28C840F3B0CBD8145965F714" s:id="{4888ABBB-F17D-4485-B14B-842413F88732}" /></conditions><actions /></rule></ruleset></rls></r></d></r>
```

Note that I did not receive any exceptions during any of this testing, however I was also on Sitecore 8.2 Update-3, so if this is a Sitecore bug it is entirely possible that it was fixed. FWIW, the UID format above is a valid `ShortID` format in Sitecore terms.

Or am I missing something? Can you provide steps to reproduce, if my testing does not match your scenario?

**Comment by ricardoazeitona** [comment]
Hello kamsar,

Thanks for the answer, yes your are reproducing it well. I'll report to Sitecore to see this issue.

**Comment by kamsar** [comment]
Feel free to reopen in the future if there's anything more from Sitecore here.
