### ISSUE TITLE
Timeout with powershell script running on azure

### ISSUE THREAD

**Issue by luuksommers** [kamsar/Unicorn#234]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When we run a sync on an Azure based Sitecore instance, we run in the Azure Load Balancer timeout of 4 minutes, resulting in an Internal Server Error (500). The unicorn sync takes about 10 minutes to complete.

**If the current behavior is a bug, please provide the steps to reproduce.**
Install sitecore on Azure and run a sync on a large site.

**What is the expected behavior?**
A fire and polling check for the remote unicorn call or any other way to work around the timeout issue.

**Please mention your Sitecore version and Unicorn version.**
Sitecore 8.2 Update 3 / Unicorn 3.3.2

**Comment by kamsar** [comment]
This is resolved in 4.0

**Comment by zhangpengchen** [comment]
Hi @kamsar ,
We had a similar issue, is there a workaround without upgrade to 4.0?

**Comment by cassidydotdk** [comment]
What's preventing you from upgrading?   There shouldn't be any real breaking configuration changes that I'm aware of.

**Comment by zhangpengchen** [comment]
@cassidydotdk My main concern is serialization files need to be changed, and we have a lot.

**Comment by zhangpengchen** [comment]
Great, thanks. Then I should give a try.
