### ISSUE TITLE
After enabling NewItemsOnly also, old items are getting updated

### ISSUE THREAD

**Issue by AbhishekKumar26** [kamsar/Unicorn#235]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
We want to ensure that only new items get synced to Sitecore. We enabled the config Unicorn.Configs.NewItemsOnly. Once we tried to sync using Powershell, old items were also updated.
**If the current behavior is a bug, please provide the steps to reproduce.**
In an existing solution, we renamed the Unicorn.Configs.NewItemsOnly.Example to Unicorn.Configs.NewItemsOnly.Config. We took an update from the source control. So, an existing yml file got updated. We executed the Powershell command to sync the ymls. The Sitecore item corresponding to this yml also got updated.
**What is the expected behavior?**
The existing item in Sitecore should not have been updated.
**Please mention your Sitecore version and Unicorn version.**
Sitecore version 8.2 rev 170407   Unicorn:3.3.2

**Comment by kamsar** [comment]
new items only is added on a per-config basis. Enabling the sample config will add a new configuration, and won't affect any existing configurations you've already defined.

You'll want to take the evaluator and put it on your config(s) you want to become new items only.

You can verify that NIOE is activated by viewing config details in the control panel for each config.

**Comment by AbhishekKumar26** [comment]
Hi Kamsar,
Can we create an exception on the basis of the template of the item?
I want that images inside media folder based upon Image template is not updated but files based upon File template gets updated.

Thanks in advance.

**Comment by kamsar** [comment]
Yes you can. It's in the docs (mobile ATM) and in the v4 launch post.
