### ISSUE TITLE
Error Installing Rainbow.Storage.Yaml 2.0.0 Nuget package

### ISSUE THREAD

**Issue by eh-ssuryana** [kamsar/Unicorn#236]
Hi,

I am unable to install unicorn 4.0, 

Looks like NuGet is getting a 404 for https://api.nuget.org/packages/rainbow.storage.yaml.2.0.0.nupkg

Getting the exact same error when using both UI and package manager

So, it is rolling back all other packages (of unicorn).

Thanks.

**Comment by kamsar** [comment]
You may be attempting to install with a nuget 3 feed? It's definitely
published (and has 277 downloads).

https://www.nuget.org/packages/Rainbow.Storage.Yaml/
