### ISSUE TITLE
Bug: Revert tree (items not controlled by Unicorn) not working with Unicorn 4.0.0

### ISSUE THREAD

**Issue by hombreDelPez** [kamsar/Unicorn#237]
**Do you want to request a *feature* or report a *bug*?**
Possible bug.

**What is the current behavior?**
The *Revert tree* button from the *DEVELOPER* ribbon doesn't sync the items back from the file system when the items are not controlled by Unicorn:
![image](https://user-images.githubusercontent.com/20950007/27686890-ffb14954-5cd4-11e7-8142-430b9a8bc4b1.png)
The other two buttons *Revert item* and *Revert database* however work as expected.

It is also interesting that the *Serialize tree* button is not working (items not controlled by Unicorn) when using Unicorn 3.3.2, [see this bug report](https://github.com/kamsar/Unicorn/issues/219). I had the same behaviour on various solutions and even on a completely clean solution. With Unicorn 4.0.0 the serializiation works but not the deserialization.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Install a clean Sitecore 8.2.x instance with Unicorn 4.0.0
- Choose a item with child items which is not under controll of Unicorn and *Serialize tree* with the *DEVELOPER* ribbon
- Delete one of the child items in Sitecore or change the values of some of the child items on the file system
- Now revert this tree via the *DEVELOPER* ribbon
- Nothing happens

**What is the expected behavior?**
- The tree in Sitecore should have the same state as the items in the file system

**Please mention your Sitecore version and Unicorn version.**
Sitecore 8.2.1 with Unicorn 4.0.0

**Comment by kamsar** [comment]
Good catch. I'm going to close this and leave #238 open for the fix.
