### ISSUE TITLE
Serialized folder became "Access Denied"

### ISSUE THREAD

**Issue by danteciambella** [kamsar/Unicorn#239]
I don't know if the following behaviour is a bug or a wrong configuration.

We are using Sitecore 82u3 and unicorn 3.3.2
Some times after the serialization process some Feuture or Foundation folder (C:\Progetti\Sitecore\<projectname>\Sitecore.<projectname>\src\Feature\Navigation\serialization\Feature.Navigation.Media) became unaccessible with "Access Denied" message. 
The only way to unlock is to use a Linux USB instance and rename/delete the folder.

There is some one experienced in this behaviour.
Dante

**Comment by kamsar** [comment]
This can occur if a folder is placed into a 'pending delete' state by the
file system. Usually killing w3wp.exe will resolve it. I've never seen
needing to use a Linux USB to fix it however, or outside of a
reserialization.

Rainbow 1.4.2 and later greatly mitigate the chances of this happening.

**Comment by danteciambella** [comment]
Ok Kamsar thank you very much for your answer.
Next time I'll try stopping w3wp.exe, I'll keep you updated.

Dante

**Comment by ESHughes** [comment]
@kamsar I cannot thank you enough for your recommendation to kill w3wp. I wasted probably a couple hours troubleshooting this. Killing w3wp immediately fixed it.
