### ISSUE TITLE
Unicorn issue | Sitecore.ContentSearch Version=2.0.0.0 

### ISSUE THREAD

**Issue by prashant3mishra** [kamsar/Unicorn#240]
When using unicorn 3 with sitecore 8.2 update 3.

We are getting below exception while installing packages on our sitecore instance

Could not load type 'Sitecore.ContentSearch.IIndexOperationsEx' from assembly 'Sitecore.ContentSearch, Version=2.0.0.0

We observe unicorn is using Sitecore.ContentSearch, Version=2.0.0.0 but we have Sitecore.ContentSearch, Version=2.0.1.121 in our bin as part of sitecore installation 

Please help!

**Comment by kamsar** [comment]
Unicorn is built against Sitecore.ContentSearch from 8.2.160729 from the official Sitecore NuGet feed. You may need to add a binding redirect for the content search assembly.

Unicorn - at least the latest 3.3 branch - definitely works with 8.2 update-3. In my case, as I was using NuGet for my Sitecore references, I suspect the binding redirect was handled automatically.
