### ISSUE TITLE
Unicorn sync is not stopping

### ISSUE THREAD

**Issue by shafaqat309** [kamsar/Unicorn#246]
We are migrating sitecore from 7.2 to 8.1 and want to serialize and sync all user defined items.

I am serializing all content nodes, user defined template, user defined layouts and user defined assets from media library. Every thing is working fine except content node, unicorn successfully serialize content node but when I sync on a fresh 8.1 database, it just keep syncing and does not stop. here is my configuration

<include database="master" path="/sitecore/content/Home">

No error, not warning but it just keeps syncing.

**Comment by kamsar** [comment]
What version of Unicorn is this on? Do any items sync on this configuration? Is transparent sync and/or dilithium enabled?

**Comment by shafaqat309** [comment]
Does the sync order matters? means syncing content nodes first and template later? or is there any sequence I need to follow?

**Comment by kamsar** [comment]
Yes. Configurations can have dependencies on each other.
