### ISSUE TITLE
No `App_Config` folder appear when installing on .Net Core Class Library

### ISSUE THREAD

**Issue by sergeyshushlyapin** [kamsar/Unicorn#247]
I've got a .Net Core Class Library project targetring .Net 452 so that I can use the assemblies under Sitecore 8.2:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Unicorn" Version="4.0.2" />
  </ItemGroup>

</Project>
```

The Unicorn assemblies appear under the `bin` folder but unfortunately the `App_Config` folder is missing Though, it appears if I install the package on a regular .Net Framework 452 project.

Is this a Unicorn nuget package issue?

**Comment by kamsar** [comment]
It's a limitation of Nuget 3 which is required for .net core. It no longer
supports solution files being deployed from packages.

The workaround is to get the config out of the GitHub repo or from the
Nuget package manually.

**Comment by sergeyshushlyapin** [comment]
Yep... That is what I did to solve that. Thanks!
