### ISSUE TITLE
Access to Unicorn control panel is not restricted for Single Server Sitecore Instance

### ISSUE THREAD

**Issue by GlennHaworth** [kamsar/Unicorn#255]
We're currently using Sitecore 8.1 Rev. 151207 and Unicorn 3.2.0 on a single server setup and what we're seeing is that you can navigate to the Unicorn control panel and see the sync and reserialize buttons when not logged in.

Not sure if this is bug which is fixed in a later release or a miss config on our part?

**Comment by kamsar** [comment]
Turn debug compilation off in the web.config.

**Comment by GlennHaworth** [comment]
Thanks Kam, sorted.
