### ISSUE TITLE
Suggestion: Allow disabling of sync on a pr. configuration basis

### ISSUE THREAD

**Issue by caroen** [kamsar/Unicorn#257]
Hi Kam,

Big fan of Unicorn, so i figured i would add a suggestion that I think would make it even better!

We all know that keeping development environments up2date with content from production environments is a real hassle, often involving database backups etc. Unicorn ofcourse lets us get around this!

However, a human error might occur where someone accidentally syncs content on a production environment, so it would be awesome if it was possible to disable sync for a given configuration.

**Comment by kamsar** [comment]
How would you differentiate between a human and a CI process doing a sync? IMO, there ought not to be any configurations on production that are dangerous to sync. If it's content, then either remove the config outright on production, use the new items only evaluator, or consider a tool such as Sitecore Sidekick Content Migrator to pull production content down to lower environments.

**Comment by caroen** [comment]
Thanks for mentioning Sitecore Sidekick, it fits my needs perfectly!
