### ISSUE TITLE
physicalRootPath in multiple configurations being overwritten

### ISSUE THREAD

**Issue by RizziFrank** [kamsar/Unicorn#258]
**Do you want to request a *feature* or report a *bug*?**
I think it's a bug, unless it was intended, in which case I'd like it added as a feature.
**What is the current behavior?**
I have two Unicorn.Configs in my Include/Unicorn directory, each with a different physicalRootPath, but all the serialization is done to only one of the paths.
**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create two different copies of Unicorn.Configs.Default.example
- e.g.:
  Unicorn.Configs.A.config
  Unicorn.Configs.B.config
2. Set the name to two different names
e.g.:
in config A:  "FolderA"
in config B:  "FolderB"
3. Set the targetDataStore physicalRootPath to a different folder for each configuration. 
- e.g:
in config A:  C:\FolderA
in config B:  C:\FolderB

4. Chose a different Sitecore path to sync in each
e.g.:
in config A:  <include name="TestFolderA" database="master" path="/sitecore/content/Home/Item1">
in config B:  <include name="TestFolderB" database="master" path="/sitecore/content/Home/Item2">
5. Sync.

All serialization files turn up in FolderB! 

**What is the expected behavior?**
That everything included in A goes to FolderA and everything included in B goes to FolderB.
**Please mention your Sitecore version and Unicorn version.**
Sitecore 8.2, Unicorn 4.0.2.0

**Comment by RizziFrank** [comment]
I wanted to give some more information.

I thought I could get around this by putting the targetDataStore physicalRootPath in one place, and then not specifying it in the other configuration files. But this made it use the default physicalRootPath that was specified in the Unicorn.config, which is expected. This leads me to believe that this is a bug, because if it falls back to the path in <defaults> when not specified, then one configuration should not have any affect on another.

**Comment by kamsar** [comment]
Can you share the exact configurations you're using, so I can inspect them?

**Comment by RizziFrank** [comment]
As I was attaching my configs I retested one more time and noticed that the problem may not be what I originally thought. I think that it only looked that way. I had not realized there were multiple "Initial Serialization" buttons, so I was only hitting the first one. I don't know why I didn't notice that the items of the second configuration file weren't being written at all and assumed that they were all being written to the same place. Also, the fact that one configuration had a physicalRootPath that was a parent of the other two didn't help.
