### ISSUE TITLE
Sync templates to cd server

### ISSUE THREAD

**Issue by Ngschumacher** [kamsar/Unicorn#261]
Hi, first of all, thank you for creating Unicorn. It has helped quite i bit in terms of updating templates etc when deploying. Thumbs up!

So at the moment i'm working on automating our deploymentprocess as much as possible, and i need to have the unicorn sync automated.
 - I have succesfully used the powershell script to run on the CM server and its working great. 

Here is my question: 
How do i manage, via configurations or something else to be able to run a sync towards my CD servers (one at the time, as a step of deployment towards these) from the CM server? 
I do not want to have unicorn or anything on my CD servers, i want to have the option of publishing from unicorn on the CM server towards to the CD servers.

I know this can be done if i do all at once, web,cd1 and cd2. But we do not want to sync templates towards a server which dosn't have the new code on it yet.

Can you give me some guidance on how to do this?

**Comment by kamsar** [comment]
Sync usually only runs on the CM, and the templates etc make it to CD via
publishing. There's an auto publish task which is enabled by default that
publishes synced items after a successful sync. You can disable or alter
this if you wish.

**Comment by Ngschumacher** [comment]
@kamsar Yeah! 
- How would i be able to run this auto publish seperatly without a sync. Because the sync has happended, i just need to wait to publish untill the right time. . 

Any guidelines?

**Comment by kamsar** [comment]
To run a publish separately you'd need to remotely invoke the publishing
API, for example with Sitecore powershell extensions remoting. Unicorn
publish is tied specifically to items synced so no sync no publish.
