### ISSUE TITLE
Missing Tools folder/PSM1 file in Version3.2.0 - NuGet Package Manager

### ISSUE THREAD

**Issue by Tirumala-K** [kamsar/Unicorn#262]
Hi, 
When I install the version3.2.0 due to the .NET framework constraint of my solution through NuGet Package Manager, I am missing the Tools folder specified (at least missing the important Unicorn.psm1 file) which is required for Automated Tool API Syncing.

Could you please provide the file or tools folder for the version?

Thanks,
Tirumala

**Comment by kamsar** [comment]
That version was prior to the tools folder. You can get the right ones from
the repository at the tag for that version.
