### ISSUE TITLE
CopyTo: the generated yml has wrong Parent ID

### ISSUE THREAD

**Issue by dplutino** [kamsar/Unicorn#264]
Hi,

I experienced an abnormal behavior.
I have the following tree under a Unicorn configuration:
`
- a
- b
    - c
`

If I do a CopyTo of item "c" into "a", the generated "/a/c.yml" has the ID of "b" (instead of the ID of "a") in the "Parent" field. If I reserialize "c", the Parent field becomes correct.

- Sitecore 8.1 (rev. 160519)
- Unicorn 3.1.1
- Lot of Helix modules deployed (I eredited a solution...)

If needed, I can send the showconfig.aspx xml.

Thanks

**Comment by kamsar** [comment]
Upgrade to the latest 3.2.x version. Pretty sure that is a fixed issue.

**Comment by dplutino** [comment]
I upgraded to 3.2.0 and now it works!
Thanks a lot
