### ISSUE TITLE
Files not changed when pushed

### ISSUE THREAD

**Issue by cmasterd** [kamsar/Unicorn#269]
This is more of a question then anything.

I need to make updates to two files, ExperienceEditor.js and RibbonPageCode.js. When I do the changes and push they don't appear on the other server. Checked the logs and I get "Deployed Sitecore version was up to date according to sitecore.version.xml. *Skipping sync of Sitecore system files.*" 

Is there a deployment script I need to change to allow me to update these files?

I am running Version Sitecore.NET 8.1 (rev. 151207) and Unicorn 3.3.1

**Comment by kamsar** [comment]
Unicorn doesn't do any file deployment itself; it looks like you may be
using some other script to do that deployment.

Given the error, you may wish to make an inconsequential change to the
sitecore.version.xml (ie add a space to the copyright text) to force a
deployment of the system files.

**Comment by cmasterd** [comment]
My mistake I'll remove this.
