### ISSUE TITLE
Unicorn uses entity references in plain text log file

### ISSUE THREAD

**Issue by arencambre** [kamsar/Unicorn#270]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Detailed error messages include entity references. See line 421 of the attached error output, copied from Visual Studio's Task Runner Explorer window.

**If the current behavior is a bug, please provide the steps to reproduce.**
Cause some deserialization error that makes Unicorn provide a detailed message.

**What is the expected behavior?**
That in plain text log files, entity references are never substituted for the proper characters. 

**Please mention your Sitecore version and Unicorn version.**
Sitecore 8.2 Update-5
Unicorn 4.0.0
[Unicorn output.txt](https://github.com/kamsar/Unicorn/files/1601661/Unicorn.output.txt)

**Comment by kamsar** [comment]
There are limitations to splitting output types between the HTML console
and text output, and occasionally compromises had to be made to favor one
format or another. This is one of them.

If you feel strongly about fixing it and submitted a PR I'd consider it,
but I don't plan to fix it otherwise.
