### ISSUE TITLE
Could not find configuration node: databases/database[@id='master']

### ISSUE THREAD

**Issue by Pjm1974** [kamsar/Unicorn#271]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your Sitecore version and Unicorn version.**

**Comment by JamesSkemp** [comment]
@Pjm1974 FYI this doesn't appear to have any actual information in the description.

**Comment by Pjm1974** [comment]
Sorry guys - I figured out what it was, the SwitchMasterToWeb.config file was being included and when I tried to run unicorn I was getting the exception Could not find configuration node: databases/database[@id='master']
