### ISSUE TITLE
Feature request: Filter users from Active Directory or list users in role

### ISSUE THREAD

**Issue by JamesSkemp** [kamsar/Unicorn#273]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

We're using Active Directory (using https://dev.sitecore.net/Downloads/Active_Directory.aspx) for the majority of our users, and giving those users custom roles if they should have Sitecore access. If we sync them via Unicorn.Users - `<include domain="adDomain" />` - then we get all 1000+ users, even those who don't have access to Sitecore / no roles defined.

There doesn't appear to be a way to restrict the pull only to those users who have explicit access defined in Sitecore, since the user name pattern match wouldn't be sufficient for our needs.

**If the current behavior is a bug, please provide the steps to reproduce.**

n/a

**What is the expected behavior?**

Would it be possible to either get users added to the roles serialization (like serialized users include a definition of roles), or somehow configure Unicorn.Users to only sync users with a particular / any Sitecore role?

**Please mention your Sitecore version and Unicorn version.**

Sitecore 8.2 rev. 170728, Unicorn 4.0.3.

**Comment by kamsar** [comment]
While I can understand your use-case, it would be very difficult to support multiple possible serialization styles. As a possible option, you can implement your own custom `IUserPredicate`, where you can use any logic you can imagine in C# or discover via Sitecore APIs to decide to include a user or not:

https://github.com/kamsar/Unicorn/blob/d69d5ad366d8567ad0653757870ee0f5ae839959/src/Unicorn.Users/UserPredicates/ConfigurationUserPredicate.cs#L50
