### ISSUE TITLE
Sitecore XP 9.0 Update 1 Compatibility

### ISSUE THREAD

**Issue by devstack** [kamsar/Unicorn#276]
Is the latest version of Unicorn compatible with Sitecore XP 9.0 Update 1?

**Comment by kamsar** [comment]
It should be yes. 




On Tue, Jan 30, 2018 at 6:27 AM -0800, "devstack" <notifications@github.com> wrote:












Is the latest version of Unicorn compatible with Sitecore XP 9.0 Update 1?
