### ISSUE TITLE
Feature request: ability to only include 1 level of children

### ISSUE THREAD

**Issue by caroen** [kamsar/Unicorn#278]
Looking at issue [#86](https://github.com/kamsar/Unicorn/issues/86) and [TestConfiguration.xml](https://github.com/kamsar/Unicorn/blob/ce1e7aacdb65d53cffa617f8a11106dd70b944e0/src/Unicorn.Tests/Predicates/), I don't seem to be able to include a certain item and only the immediate children of that node.

My specific need is that in combination with Unicorn.Roles serializing my editor roles, I am assigning role access to a set of sibling site-nodes, but dont want any of their descendants serialized - I am currently able to fulfill that need by having a predicate with the following include rule:
```
<include name="SiteRootsA" database="master" path="/sitecore/content/sites type A">
  <exclude childrenOfPath="site A1" />
  <exclude childrenOfPath="site A2" />
</include>
<include name="SiteRootsB" database="master" path="/sitecore/content/sites type B">
  <exclude childrenOfPath="site B1" />
  <exclude childrenOfPath="site B2" />
</include>
```

But with this approach, every time I add another site of either type, i have to manually opt-out of the serialization - it would be nice if instead there was a `depth` attribute on the `<include />` tag so I could just assign `depth="1"` to only include the immediate children.

**Comment by kamsar** [comment]
I'd be happy to entertain a PR with tests that adds this, but I don't plan to implement it myself due to free time constraints.
