### ISSUE TITLE
Feature request : Security serialization/revert

### ISSUE THREAD

**Issue by el-slowmo** [kamsar/Unicorn#30]
Hi, 

I've been using Unicorn in my latest Sitecore implementation and it's been a great help.
One thing I'd love to see added though is a means to serialize and revert specific domains, roles and users with Unicorn.

Typically I leave the Sitecore domains and roles alone, but for most projects I usually add a domain for the project and some roles for them, and also include those roles into my source control.
Sitecore serializes those into a \serialization\security\ folder.

It would be cool if the Unicorn serialization.config would 
%lt;include database="security" path="/xyz/Roles/ContactRole" /%gt;
%lt;include database="security" path="/xyz/Roles/LeadRole" /%gt;
%lt;include database="security" path="/xyz/Users/CustomerAdminUser" /%gt;

Kind regards,

**Comment by amitthakur2014** [comment]
Hi Kamsar,

Just wanted to know , the new functionality got implemented in new version of Unicorn

**Comment by kamsar** [comment]
Nope. It's not there yet.

**Comment by cassidydotdk** [comment]
I don't think serialisation of security related information belongs in Unicorn, just my 2 cents. Changes to users/roles happen so infrequently in a project life cycle, managing process around this is not really a prime candidate choice for automation.

**Comment by el-slowmo** [comment]
I disagree.  It is serializeable sitecore content that your code can depend
on.

For instance if you want to add user registration/authentication on your
site by using Sitecore users in a specific domain.  You will want to
serialize that domain and add it to your source control, so you can deploy
the code and the sitecore items including the domain that go with your code.

**Comment by kamsar** [comment]
Serialization of users, absolutely not.
Serialization of roles, I think makes sense.
Suppose you have a very multi site solution where each site has its own
roles, or devs are defining workflows and need to push dependent security
roles for the steps and transitions.

It is a totally separate concern from regular unicorn though as roles are
just a string and not an item. That's why this has sat on the shelf for so
long. New infrastructure for everything.

**Comment by Eldblom** [comment]
My opinion is that we should be able to serialise and version control *everything* if you wish to do so. This includes roles and users. 
Naturally it's not sound to version control production users (or content for that matter) but for e.g. regression test purposes it is vital that you can store and version control complete environment configurations.

**Comment by kamsar** [comment]
There's no way to serialize users' passwords (or even the hashes thereof without direct SQL calls) which makes serializing users a bit pointless imo, as any deserialized user would only really be usable by a `UserSwitcher` or something as the password would not be moved.

**Comment by Eldblom** [comment]
Good point. A file based membership provider could be the way to go for the automated test scenario.

**Comment by cassidydotdk** [comment]
While there may be a case for security information serialisation, I still don't see this as the job of Unicorn. It deals with Sitecore content in Sitecore databases. Membership data is neither content, nor does it sit in Sitecore databases.

A new tool, possibly as @Eldblom suggests; file based membership, profile, and role providers - sure. Would be reasonably easy to implement as well. Or grab an existing one:

https://github.com/wilby/XmlMembershipProvider

**Comment by kamsar** [comment]
Moving this conversation to #107
