### ISSUE TITLE
"inconsequential" changes to items

### ISSUE THREAD

**Issue by michael-huxtable** [kamsar/Unicorn#32]
We have been evaluating Unicorn for a while now and it seems to be working rather well, except that when we add/edit/delete a field within Sitecore our pending changes list shows a lot of edits that are just the version, revision and date updated for that particular template e.g:

```
----version----
language: en
version: 1
revision: f09e2cd1-7c20-409d-9fdf-65778c8f336d

----field----
field: {8CDC337E-A112-42FB-BBB4-4143751E123F}
name: __Revision
key: __revision
content-length: 36

31a9c5c9-672b-4c7b-9841-59b08d140165

----field----
field: {D9CF14B1-FA16-4BA6-9288-E8A174D4D522}
name: __Updated
key: __updated
content-length: 34

20140902T094036:635452476360564977
```

I'm not entirely sure if we are missing some piece of config or if this is even avoidable but it seems fair enough, it's just I read the inconsequential changes feature and it sounds like it would prevent these changes?

**Comment by kamsar** [comment]
This will be fixed in the next release. It appears the change detection classes occasionally - e.g. when saving templates - report that a property (eg name, template) was "changed" and the value remained identical. Yeah, we don't care if the value was identical.

**Comment by kamsar** [comment]
Thanks for the issue report, and sorry it took so long. Was also driving me nuts for what its worth :)
