### ISSUE TITLE
SerializationPresetPredicate configuration with presetName attr throws exception

### ISSUE THREAD

**Issue by kbalcerek** [kamsar/Unicorn#37]
Hi,

After I configured Unicorn to use shared serialization preset it started to throw exception. The configuration I did is:
```
<predicate type="Unicorn.Predicates.SerializationPresetPredicate, Unicorn" presetName="default" singleInstance="true" />
```

and

```
<sitecore>
    <serialization>
      <default>
        <include database="core" path="/sitecore/system/Field types"/>
      </default>
    </serialization>
</sitecore>
```

The exception thrown is:
Error activating IPredicate using binding from IPredicate to SerializationPresetPredicate
Several constructors have the same priority. Please specify the constructor using ToConstructor syntax or add an Inject attribute.

Constructors:
SerializationPresetPredicate(string presetName)
SerializationPresetPredicate(XmlNode configNode)

I probably misunderstood how to configure it, but have no other idea how to make it work. Could you help?

**Comment by kamsar** [comment]
Most likely a bug; as a workaround you can try using a local predicate specification. I'll look at this next time I do some maintenance on Unicorn.

**Comment by kamsar** [comment]
Out of curiosity, what was the use case where you wanted the shared preset? That functionality is mostly there because that's what Unicorn 1.x used, and I can't think of a reason I'd use it.

Maybe you can, in which case do tell before I simply remove the feature.

**Comment by kamsar** [comment]
Closing this. Preset name support will be removed in Unicorn 3.

**Comment by kbalcerek** [comment]
Hi kamsar, I'm sorry for replying so late.

I wanted to use "presetName" attribute in order to avoid having exactly the same configuration (Sitecore serialization preset) in two places (Serialization.config - for Unicorn, and the one under /sitecore/serialization/default - for Sitecore).

As far as I remember configuration under /sitecore/serialization/default was needed to enable auto serialization after changes in sitecore - but I'm not sure right now (I don't remember)
