### ISSUE TITLE
Support for field sharing changes

### ISSUE THREAD

**Issue by rootix** [kamsar/Unicorn#39]
Hi,

We experience a conceptual issue / missing feature of Unicorn (This is a Feature request =)).

If i change the sharing setting of a field from Shared to Versioned, Sitecore triggers a background job to move all field data of this field from the SharedFields into the VersionedFields table. The sharing type is correctly changed and serialized trough Unicorn. Everything is fine on my machine.

Howevery, if another developer deserialises the changes on his machine, the field is set to unshared, but the data remains in the SharedFields table which makes field value changes impossible on the depending items. Every time you want to change an item value (the shared value is shown in every version), the change is silently ignored and the old value appears again after reloading the item.

There are some methods in the FieldSharingConverter class (which is placed inside the SqlDataProvider class) to change the values for a specific field id (e.g. MakeVersioned with a parameter in which the old sharing type is provided). Those methods seem to be triggered in the Content Editor after changing such a sharing flag. 

**Feature request:**
Detect changes in the field sharing settings while syncing and update the database inside your DataProvider to leave the items intact (This can be an asynchronous task per changed field).

Regards,
Pascal

**Comment by kamsar** [comment]
Will keep it in mind, thanks :)

**Comment by kamsar** [comment]
This is now supported in Rainbow (lib for Unicorn 3.0): https://github.com/kamsar/Rainbow/commit/f4930c3c1dd092fa3274bbe29f0cb811c37f98b9

**Comment by kamsar** [comment]
FWIW, the task is executed synchronously. This is intentional, because at least in my usage occasionally Unicorn will run around an app pool restart. That causes background tasks to terminate, as it waits for executing requests to complete. Which would leave you with a munged DB if it was a backgrounded thing.
