### ISSUE TITLE
Sitecore.Social requires Ninject, Version 3.2.0.0

### ISSUE THREAD

**Issue by nemanuel** [kamsar/Unicorn#40]
In Sitecore 8.0 rev. 150223 the following warning is thrown in the Sitecore log file.

- Sitecore.Social: Ninject, Version=3.2.0.0, Culture=neutral, PublicKeyToken=c7192dc5380945e7 is not loaded. The task execution is skipped.

As Unicorn is dependent of Ninject, Version 3.0.1.10 these two are not working very well together. Can you upgrade Ninject to version 3.2.0.0 in the unicorn solution?

**Comment by pierrebakker** [comment]
Unfortunately I have the same issue. Unicorn is not compatible with Sitecore 8. When do you expect to upgade ninject fot the solution?

**Comment by kamsar** [comment]
The next release will have this; in the meantime, a binding redirect works just fine (I have Sitecore 8 sites in production with Unicorn):

    <dependentAssembly>
        <assemblyIdentity name="Ninject.Web.Common" publicKeyToken="c7192dc5380945e7" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.2.0.0" newVersion="3.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Ninject" publicKeyToken="c7192dc5380945e7" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.2.0.0" newVersion="3.2.0.0" />
      </dependentAssembly>

**Comment by nemanuel** [comment]
Thanks kamsar! That will work for now.

**Comment by pierrebakker** [comment]
Thx! works for now!
