### ISSUE TITLE
Integration with TFS server workspace not possible?

### ISSUE THREAD

**Issue by Joentje71** [kamsar/Unicorn#46]
Hello,

We use unicorn in combination with Visual Studio 2013 and TFS 2013. 

When I make a change to an existing item in Sitecore, Unicorn tries to change the associated item on disk, but then raises an error: access to the path ... is denied. Also, the item in the serialization project is NOT checked out.

My Workspace is a "server workspace". All items on disk are read-only. Unicorn seems to have no rights to check out an item, make the item on disk writable and write changes to it.

Other developers in my team have a "local workspace". All their items on disk have the read-only flag NOT set. Unicorn is able to check the item out in TFS and make changes to the file on disk.

But I want to keep using a server workspace. Its performance is better when you have lots of items. TFS 2013 introduced the concept of a local workspace. Workspaces in earlier TFS versions were always on the server.

Is Unicorn not capable of working in combination with a TFS server workspace? 

Thank you for your advice!

Greetings,
Jeroen

**Comment by kamsar** [comment]
Unicorn has no explicit support for TFS; I've prototyped it with VSO and a local workspace and yes, it seems to work. However if all files are locked and TFS must be contacted to unlock it - it's probably not going to work.

Your only option would be to implement your own version of the serialization provider that called some sort of TFS API to unlock the item before a write. I have no idea if such an API exists, and it may cause problems for the other developers not using a server workspace.

On the whole, using a server workspace with Unicorn is probably not a good idea. Using Git would be an even better idea :)

**Comment by Joentje71** [comment]
Thank you for your reply and tips! For now, we all are going to use a local workspace. 

For legacy (BIDS) projects we'll have to configure a second workspace, because older versions of Visual Studio do not support local workspaces.
