### ISSUE TITLE
Unicorn is taking 5 Hours to complete sync Operation

### ISSUE THREAD

**Issue by pradsir** [kamsar/Unicorn#47]
Hi Kamsar,

We have around 15000 items created by us in sitecore. 

The database size for master database is around 6 GB.

It takes around 5 hours to complete the sync operation.

We have already mitigated the system out of memory exception by increasing the ram ,etc.

Please suggest ways to reduce the sync time.

We have excluded item for time being in order to process items faster.

Many Thanks

**Comment by kamsar** [comment]
Unicorn is intensive in two primary ways: it needs to read the serialized items from disk, and call the Sitecore database to read the items from there.

The biggest speedup you can usually accomplish is by reading the files and database items from SSDs. For example, on my all SSD dev machine using a local database I just ran a sync over the complete stock core and master databases in 70 seconds, which is 19,182 items.

That said, if you are syncing your entire 6GB database you'll never see very good sync speeds. Unicorn is designed to sync only development artifacts (layouts, renderings, templates, for example) in a reasonable timeframe.

If you're aiming to do a content migration in bulk or something like that, you may have better luck using the built in serialize/revert tree functions of Sitecore as they do not compare, only read and replace.
