### ISSUE TITLE
Error Including Single Item w/Default Predicate

### ISSUE THREAD

**Issue by williamsk** [kamsar/Unicorn#50]
Using Unicorn 3.0 b8.

Here's the `<include>` that I added to the stock `<predicate>`

`<include database="master" path="/sitecore/media library/SUGBG/Hero Images/_Default Hero" />`

This is a single image item within the media library.  I didn't do any further testing to see if this happens with any item anywhere or if it's unique to media.  Here's the error showing up in the Unicorn console:

> Unable to resolve root serialized item for predicate root path master:/sitecore/media library/SUGBG/Hero Images/_Default Hero. Either the path did not exist, or multiple items matched the path. It has been skipped.

**Comment by kamsar** [comment]
Very odd. I just did the same thing with `<include database="master" path="/sitecore/media library/Public/_Jellyfish"/>`, both with and without the leading underscore. It worked.

You don't have two items named `_Default Hero` do you? If the path is non-unique it'll throw that. I'm assuming you've checked that there are no typos in the path?

Is there anything security related that might be getting in the way? Unicorn does use SecurityDisabler during dump and sync, but might be a bug or something.

**Comment by williamsk** [comment]
Only one item named _Default Hero (and at the moment, it's the only item in that folder).  I copy/pasted the path from Quick Info in Content Editor, so I'm fairly sure that's right. :)

No security has been applied at all.

It's Sitecore 8 Update 4 (not Update 5) in case that makes a difference.

Media Library looks like this:
![Screenshot of Media Library](http://i.imgur.com/pjcDD6z.png)

Here's the relevant configuration (copy/paste from showconfig.aspx):

`<targetDataStore type="Rainbow.Storage.SerializationFileSystemDataStore, Rainbow" physicalRootPath="C:\Projects\KNW.SUGBG.Website\items" useDataCache="false" singleInstance="true" patch:source="SUGBG.config"/>`
`<predicate type="Unicorn.Predicates.SerializationPresetPredicate, Unicorn" singleInstance="true">`
`<!-- snip -->`
`<!--`
` Specific media library images that we want source controlled (used in standard values, etc) 
-->`
`<include database="master" path="/sitecore/media library/SUGBG/Hero Images/_Default Hero" patch:source="SUGBG.config"/>`

I can test again with Sitecore 8 Update 5 and/or b9 of Unicorn tonight.

**Comment by kamsar** [comment]
From Slack:

on that media error had you done an initial serialization yet?
because that error is because Unicorn can't read the root ​_serialized_​ item, not the sitecore item
maybe it's just not written yet?
