### ISSUE TITLE
Could not resolve type name: Unicorn.UnicornSqlServerDataProvider, Unicorn (method: Sitecore.Configuration.Factory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).

### ISSUE THREAD

**Issue by ramnkl** [kamsar/Unicorn#52]
I tried to install Unicorn 3.0 RC 
below is the nuget package details

  <package id="Unicorn" version="3.0.0-rc1" targetFramework="net451" />
  <package id="Unicorn.Core" version="3.0.0-rc1" targetFramework="net451" />

We are in the process of the auto deployment process with unicorn. It would be more helpful for us to resolve this issue.

I have also tried with sample config which are included while install the nuget package.

Server Error in '/' Application.

Could not resolve type name: Unicorn.UnicornSqlServerDataProvider, Unicorn (method: Sitecore.Configuration.Factory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Exception: Could not resolve type name: Unicorn.UnicornSqlServerDataProvider, Unicorn (method: Sitecore.Configuration.Factory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[Exception: Could not resolve type name: Unicorn.UnicornSqlServerDataProvider, Unicorn (method: Sitecore.Configuration.Factory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).]
   Sitecore.Diagnostics.Error.Raise(String error, String method) +137
   Sitecore.Configuration.Factory.CreateType(XmlNode configNode, String[] parameters, Boolean assert) +293
   Sitecore.Configuration.Factory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert) +58
   Sitecore.Configuration.Factory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +131
   Sitecore.Configuration.Factory.CreateObject(String configPath, String[] parameters, Boolean assert) +579
   Sitecore.Configuration.Factory.CreateFromReference(XmlNode configNode, String[] parameters, Boolean assert) +137
   Sitecore.Configuration.Factory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +109
   Sitecore.Configuration.Factory.GetInnerObject(XmlNode paramNode, String[] parameters, Boolean assert) +961
   Sitecore.Configuration.Factory.AssignProperties(XmlNode configNode, String[] parameters, Object obj, Boolean assert, Boolean deferred, IFactoryHelper helper) +552
   Sitecore.Configuration.Factory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +275
   Sitecore.Configuration.Factory.CreateObject(String configPath, String[] parameters, Boolean assert) +579
   Sitecore.Configuration.Factory.GetDatabase(String name, Boolean assert) +144
   Sitecore.Configuration.Factory.GetDatabase(String name) +42
   Sitecore.Configuration.Factory.GetDatabases() +98
   Sitecore.Data.Managers.HistoryManager.InitializeEventHandlers() +35
   Sitecore.Pipelines.Loader.InitializeManagers.Process(PipelineArgs args) +41
   (Object , Object[] ) +71
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +331
   Sitecore.Nexus.Web.HttpModule.Application_Start() +228
   Sitecore.Nexus.Web.HttpModule.Init(HttpApplication app) +673
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +618
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +419
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +343

[HttpException (0x80004005): Could not resolve type name: Unicorn.UnicornSqlServerDataProvider, Unicorn (method: Sitecore.Configuration.Factory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +579
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +120
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +712

**Comment by kamsar** [comment]
Are you upgrading from v2? Because that type name is v2's data provider.

There are [upgrading directions here](https://github.com/kamsar/Unicorn/wiki/Upgrading-to-Unicorn-3); specifically, you may need to remove the data provider registration from the main unicorn.config/serialization.config and allow it to register from `Unicorn.DataProvider.config` instead.

**Comment by kamsar** [comment]
There are also [clean copies of all the config files](https://github.com/kamsar/Unicorn/tree/master/src/Unicorn/Standard%20Config%20Files) here

**Comment by ramnkl** [comment]
Thanks Kamsar, It worked after remove the serialization.config from  app_config\include folder.

**Comment by JawadSabra** [comment]
Brilliant, Thanks Ramnkl and Kamsar

**Comment by sabraj** [comment]
HI @kamsar . I am still having this issue, and deleting serialization.config doesn't seem like a sensible solution as it is required to point unicorn where to pull the data from? Because when i launch unicorn after deleting the file i get a message that there is no default configuration set for serialization, then if i do serialization anyways the project is still to the default content tee.  Can you please provide any advice on this

**Comment by kamsar** [comment]
@JawSab `Serialization.config` is an artifact of Unicorn 2.x, and the configurations therein have been moved elsewhere. The [upgrade guide](https://github.com/kamsar/Unicorn/wiki/Upgrading-to-Unicorn-3) will walk you through where to put things.

**Comment by muso31** [comment]
I just upgraded to unicorn 3.0. It works and writes files to disk (wwwroot) but in Visual Studio they don't appear as items to be checked in? There's no 'serialization' folder in the project anymore so where do they get written to? In my old setup I used <setting name="SerializationFolder"> in the serialization.config but assume it's incorrect to add this to unicorn.config? thanks

**Comment by kamsar** [comment]
The default in 3.0 is `$(dataFolder)\Unicorn`. There's a sample config that is included that demonstrates how to move the default.

**Comment by muso31** [comment]
Thanks the items successfully appear here but it's not serializing item changes I make in Sitecore into VS (there is a predicate setup). They don't appear as pending changes in visual studio? I do have the correct message in Sitecore:

> This item is controlled by Unicorn
Changes to this item will be written to disk as part of the 'Default Configuration' configuration so they can be shared with others.

**Comment by kamsar** [comment]
Check your ignores. Visual studio also has the nasty habit of not showing
changes outside csproj entries.

**Comment by muso31** [comment]
Turns out the problem was the targetDataStore in unicorn config doesn't seem to be getting overridden with the one in custom serialization config. Must it be removed from unicorn.config?

**Comment by jaimeyzv** [comment]
Hi there, 

I'm having the same issue with Sitecore 9.2.0 and unicorn 4.0.3. i tried to follow the workaround you described up there but some files are no longer available (because of version i guess). Any suggestionplease? Regards.

Error: Could not resolve type name: Unicorn.Data.DataProvider.UnicornSqlServerDataProvider, Unicorn (method: Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).

**Comment by cassidydotdk** [comment]
Definitely not the same issue.

Anyway, for Sitecore 9.2.0 the minimum required version of Unicorn is 4.1.0. Update to that, clean up your config clutter.

**Comment by jaimeyzv** [comment]
Actually, I used 4.0.30 for testing since the latest (4.1.1) is throwing the same error. Also, I just reintalled 4.1.1again, create the serialization solution again and, as I mentioned, I'm getting the same error.

Based on this, unicorn update is not the fix. Any other suggestion please.

**Comment by cassidydotdk** [comment]
Yea. Harsh as it sounds; clean up your config clutter :-)    There's either DLLs missing in your target instance, or there are relic config files present in your target instance.
