### ISSUE TITLE
Illegal characters in path. when include content tree for serialization

### ISSUE THREAD

**Issue by ramnkl** [kamsar/Unicorn#54]
We are planning to use unicorn to setup the new instance after serialize all the items from sitecore from dev env.  It was working fine without content tree. When we include the content tree we are getting the below issue.  Is there a way to access the log info so that we would find out exactly which items throwing exception. 

Default Configuration is being reserialized
[D] Clearing existing items from Serialization File System Data Store
[U] Serializing included items under root core:/sitecore/system/Field types (76e6d8c7-1f93-4712-872b-da3c96b808f2)
[U] Serializing included items under root core:/sitecore/system/Settings (087e1ea5-6280-4575-9e70-85b588db91b2)
[U] Serializing included items under root core:/sitecore/content/Documents and settings/All users (78415f9a-e2f7-4b61-8a99-81c75904f1b1)
[U] Serializing included items under root core:/sitecore/content/Applications (c74ac643-53c8-4f1e-9508-840cdc72aaca)
[U] Serializing included items under root master:/sitecore/layout (eb2e4ffd-2761-4653-b052-26a64d385227)
[S] master:/sitecore/layout/Simulators (39522e9a-9b6e-4cb4-850c-23d0d3adfd0c) because Item path exclusion rule
[S] master:/sitecore/layout/Renderings/System (f4008f10-bbb2-4565-b652-467491361d5a) because Item path exclusion rule
[S] master:/sitecore/layout/Layouts/System (6e14276a-fd7f-40ec-9880-4ea96135ae9d) because Item path exclusion rule
[U] Serializing included items under root master:/sitecore/system (13d6d6c6-c50b-4bbd-b331-2b04f1a58f21)
[S] master:/sitecore/system/Aliases (5f094fe4-cc4b-40fd-9377-9ab00e7f7ca5) because Item path exclusion rule
[S] master:/sitecore/system/Marketing Center (33cfb9ca-f565-4d5b-b88a-7cdfe29a6d71) because Item path exclusion rule
[S] master:/sitecore/system/Publishing targets (d9e44555-02a6-407a-b4fc-96b9026caadd) because Item path exclusion rule
[S] master:/sitecore/system/Tasks/Schedules (a705d262-5714-4880-9962-051e25f1416d) because Item path exclusion rule
[U] Serializing included items under root master:/sitecore/templates (3c1715fe-6a13-4fcf-845f-de308ba9741d)
[S] master:/sitecore/templates/System (4bf98ef5-1d09-4dd1-9afe-795f9829fd44) because Item path exclusion rule
[S] master:/sitecore/templates/Branches/System (c93c0945-607b-4916-b8d9-fe9f9ba783ca) because Item path exclusion rule
[U] Serializing included items under root master:/sitecore/content (0de95ae4-41ab-4d01-9eb0-67441b7c2450)
ERROR: One or more errors occurred. (System.AggregateException)
at Unicorn.SerializationHelper.DumpTreeInternal(IItemData root, IPredicate predicate, ITargetDataStore serializationStore, ISourceDataStore sourceDataStore, ILogger logger) 
at Unicorn.SerializationHelper.DumpTree(IItemData item, IConfiguration configuration) 
at Unicorn.ControlPanel.ReserializeConsole.Process(IProgressStatus progress)
Illegal characters in path. (System.ArgumentException)
at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional) 
at System.IO.Path.GetDirectoryName(String path) 
at Rainbow.Storage.SerializationFileSystemTree.WriteItem(IItemData item, String path) 
at Unicorn.SerializationHelper.DumpItemInternal(IItemData item, IPredicate predicate, ITargetDataStore targetDataStore) 
at Unicorn.SerializationHelper.<>c__DisplayClass5.b__4()

Completed. Want to return to the control panel?

**Comment by kamsar** [comment]
Ok, give this assembly a shot: https://drive.google.com/file/d/0B2kWVEe9WZ4cR0d1UEFUTFdwWlk/view?usp=sharing

https://github.com/kamsar/Rainbow/commit/f5ed0b6c46026a90ac1081927b4faa96d53bfe01 fixes the invalid chars issue, and https://github.com/kamsar/Rainbow/commit/6d0869e5c73c712915abdfd4e429ef993bca89d3 fixes the error messaging not including the filename in some cases

**Comment by kamsar** [comment]
If that works, this fix will be in the next RC release.

**Comment by ramnkl** [comment]
Thanks a lot Kamsar for Quick turn around. It worked for. Please update us once it is available in the Next RC.
We are planning to replace the TDS mainly for build automation and also planning to build a code generate tool with unicorn for Glass mapper.

**Comment by kamsar** [comment]
The next RC is out, which should fix this. Let me know how it goes.

**Comment by kamsar** [comment]
I'm going to assume this is fixed; reopen if not.
