### ISSUE TITLE
Issue with Placeholder field and content as a standard value

### ISSUE THREAD

**Issue by MacDennis76** [kamsar/Unicorn#57]
Every time I do a re-sync, the following is displayed in the output:

```
[U] master:/sitecore/layout/Sublayouts/Websites/Horeca Toolbox/Social Content Generator/SCG About (427141c2-a17c-48e6-80a3-628716e3ca83)
> Field Placeholder - Serialized content, Source
```

In the source database this field value is equal to 'content', it is shared and not a standard value, it is set in the item.
In the target database this field value is also equal to 'content' but here it is a shared field and a standard value, so not yet set in the item.
When I create a new sublayout in the source database the field value is set to 'content', a shared field and also a standard value.

When Unicorn does a sync with the target it reads an empty value from the item (correct). But persisting the 'content' value from the serialized item is not done because perhaps Sitecore sees it already as a standard value and skips the saving of the value in the item?

This issue seems to have some resemblance with the __Lock field issue.

I have the same issue with other fields like __SortOrder where the value is set in the item but equal to the original standard value. I am now solving this issue by fixing it in the source database by resetting these fields back to the original standard values.

**Comment by kamsar** [comment]
As in #56 you'll have to expect odd behaviour when syncing if you've got different standard values between environments. What is your use case that requires having different standard values?

**Comment by MacDennis76** [comment]
This is a big +3 year old platform. There is no use case. :)
I fixed it manually on source and target database.
Everything is fine now, thanks.
