### ISSUE TITLE
Transparent sync and excluded paths

### ISSUE THREAD

**Issue by kamsar** [kamsar/Unicorn#61]
from Kevin Williams on Slack:

![image](https://cloud.githubusercontent.com/assets/103677/10318438/5147de6c-6c1e-11e5-99ef-dc729ee1d62a.png)

This happened when I turned on transparent sync for my configuration.  I have done an initial serialization.  I have /sitecore/templates included with /sitecore/templates/Common excluded.  So Folder is there in Sitecore (confirmed by disabling transparent sync again so that I can bring Sitecore up) but it's not there in my serialized files (since it's excluded).

**Comment by kamsar** [comment]
This occurs because TpSync takes over the database, including children, where it exists.

However, in the event that a child from the database is not part of the Unicorn configuration we should enable it to exist.

**Comment by kamsar** [comment]
This could be difficult to implement because we don't necessarily know paths when we get children and paths are a bit expensive to get. But we'll figure something out.

**Comment by kamsar** [comment]
@williamsk the more I think about this the more I think excludes should just be a no-no when using TpSync. Having a discontinuous tree that's part in the db, part on disk, and part in the db again at some leaf nodes seems like it could invite a lot of peril, 'corrupt' db states (orphaned items) or unexpected consequences due to changes in TpSync items.

What do you think?

**Comment by williamsk** [comment]
I'm fine with it.  To be honest, the explicit includes make more sense to me now that I've modified the config.  I really had just started with what's in Unicorn.Configs.Default.example, added an exclude for /sitecore/Templates/Common, and enabled transparent sync.

If you have time to create an example config for transparent sync including a comment about excludes not working with tpsync, it might help someone else not make the same mistake.  In any case, I'm fine with closing this out as I don't actually need to do it. :)

Thanks!

**Comment by kamsar** [comment]
Added notes https://github.com/kamsar/Unicorn/commit/7f07dc2ab0211efa0a682d40320e43d0c8e1a66e

Also, see the new TpSync guide for more things to not do with it: https://github.com/kamsar/Unicorn/wiki/The-Transparent-Sync-Guide
