### ISSUE TITLE
Unknown connection string. Name: '$(1)'

### ISSUE THREAD

**Issue by Jonne** [kamsar/Unicorn#63]
I get "Unknown connection string. Name: '$(1)'" after upgrading to Unicorn 3 and using the default configuration. 

I had to change the database configuration to:

					<dataProvider>
						<patch:attribute name="ref">dataProviders/unicorn</patch:attribute>
            <patch:attribute name="param1">$(id)</patch:attribute>
					</dataProvider>

And now it works. Some kind of order issue?

**Comment by kamsar** [comment]
What Sitecore version are you on?

**Comment by Jonne** [comment]
8 Update 4

**Comment by kamsar** [comment]
odd, I've run it on update 5 and update 2. Are your database configurations customized to have something other than `$(id)`?

**Comment by Jonne** [comment]
We are using Commerce Connect icw Commerce Server. Maybe this is related?

**Comment by kamsar** [comment]
Ahh. Does commerce server inject its own data provider over top of master perhaps? Check /sitecore/admin/showconfig.aspx to see merged config.

**Comment by Jonne** [comment]
No it does not. The only different i saw was in the position of the Param1 attribute.

**Comment by kamsar** [comment]
Well it doesn't seem to break anything to add it to the default config. Want me to commit it, or would you prefer to PR it?

**Comment by Jonne** [comment]
Created PR. Thanks

**Comment by kamsar** [comment]
#65 has been merged. Closing this.

**Comment by kamsar** [comment]
er #64, my bad.

**Comment by Tamaraamad** [comment]
make sure that sitecore read the unicorn congratulation the last. 
p.s change the unicorn configuration folder name to start with zzz or such.
