### ISSUE TITLE
Multiple configurations leads to multiple items in content tree

### ISSUE THREAD

**Issue by Jonne** [kamsar/Unicorn#65]
In our configuration having multiple configurations somehow results in seeing multiple item in the content tree

![capture](https://cloud.githubusercontent.com/assets/366991/10366573/a83e5b66-6dcb-11e5-9aff-eed53bb245fc.PNG)

**Comment by Jonne** [comment]
This is related to #63 . Apparently the commerce server data provider was replaced instead of the main one. PR #64 fixes this

**Comment by kamsar** [comment]
PR merged! Thanks for identifying the problem and fixing it.
