### ISSUE TITLE
FEATURE REQUEST: Silent Mode

### ISSUE THREAD

**Issue by cardinal252** [kamsar/Unicorn#68]
As requested, it would be pretty cool if we could get a 'silent' mode which would maybe just have a %age complete counter instead of a complete run down of what is going in within the browser. Am experiencing a significant portion of CPU time from the browser process (chrome) when performing a large sync operation.

**Comment by kamsar** [comment]
Short term, perhaps expose automated tool mode via a query param or something - probably would scale better.

Longer term, look at console optimizations to reduce CPU usage in the browser on long and busy  console lengths

**Comment by cardinal252** [comment]
And a button in the UI for automated tool mode please ;)
