### ISSUE TITLE
TFS 2013 does not allow $ as the beginning of a path component

### ISSUE THREAD

**Issue by WizX20** [kamsar/Unicorn#70]
When creating a branch in Sitecore, you typically create an item named $name to ensure the item is named correctly when created with the branch-template. This will create a folder $name and a file $name.yml on disk.

This is all fine untill you try to add the files to TFS 2013, you will get the exception (example):
The path '$Repo Name/App_Data/Serialized/Default Configuration/templates/Branches/User Defined/Homepage/$name/Content' contains a '$' at the beginning of a path component. Remove the '$' and try again.

As far as I know there is no work-around for this in TFS, see: [Naming Syntax, Conventions, and Limitations](https://msdn.microsoft.com/en-us/library/ms245472(v=vs.100).aspx)

Is there any way unicorn can convert/escape the $ character?

**Comment by kamsar** [comment]
This same issue has been reported in Rainbow: https://github.com/kamsar/Rainbow/issues/4, so in the interest of brevity I'm going to close this one and continue the discussion over there.
