### ISSUE TITLE
If an item is restored from the recycle bin after Unicorn deletes it, it's not serialized

### ISSUE THREAD

**Issue by kamsar** [kamsar/Unicorn#72]
(report from Slack)

Suppose Unicorn deletes an item during a sync. Then suppose you restore the deleted item from the recycle bin.

It seems that restoring from recycle bin is not causing the item to be serialized when it's re-created. It probably should do so.

**Comment by GeorgeKarbyn** [comment]
Thanks for creating the issue for me!
