### ISSUE TITLE
Ancestor renaming removes descendants

### ISSUE THREAD

**Issue by uandrei** [kamsar/Unicorn#77]
If you have a structure 2 levels+ deep and then rename the top parent, the items on the 1st level are OK, however anything on a deeper level gets deleted.

Steps to reproduce:
1. Create Item1
2. Create Item2 as a child of Item1
3. Create 2 new items as children of Item2
4. Rename Item1 to Item1New
5. Sync configuration
6. The items created at step 3 are put into the recycle bin

**Comment by kamsar** [comment]
There has to be something unique going on here. I just did the following, without error:

* Add Item1 (in this case, a template)
* Add child, Item2 (template section)
* Add two children to Item2 (template fields)
* Rename Item1 to Item1x
* Filesystem updated with the new name as well as sync making no changes

Do you have any unusual circumstances going on?

* What version of Unicorn and Sitecore are you using?
* Is Transparent Sync enabled?
* Do filesystem permissions grant Unicorn write access?
* Anything else you can think of?

**Comment by uandrei** [comment]
I've just give it a go again. Yes, in the templates section all is working fine, but in the Content part of the website on item rename the item specific folder gets recreated rather than renamed.

**Comment by kamsar** [comment]
Can you paste your configurations please?

**Comment by kamsar** [comment]
Also if you haven't, try 3.0.2. I made sure there was a specific test to
cover this scenario.

**Comment by uandrei** [comment]
Hi,

Sorry for not replying, was a bit tied up. I did try an upgrade to 3.0.2
and I've noticed that the folder structure gets created as expected,
however every time I do a rename in the /sietcore/content side I do get an
error message as per the attached screenshot.

The solution uses Sitecore 7.0 Update 2.

Any ideas?

Kind regards,
Andrei Ungureanu

On 5 November 2015 at 15:14, Kam Figy <notifications@github.com> wrote:

> Also if you haven't, try 3.0.2. I made sure there was a specific test to
> cover this scenario.
>
> On Thu, Nov 5, 2015 at 7:07 AM Kam Figy <kamsar@gmail.com> wrote:
>
> > Can you paste your configurations please?
> > On Thu, Nov 5, 2015 at 2:31 AM uandrei <notifications@github.com> wrote:
> >
> >> I've just give it a go again. Yes, in the templates section all is
> >> working fine, but in the Content part of the website on item rename the
> >> item specific folder gets recreated rather than renamed.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/kamsar/Unicorn/issues/77#issuecomment-154022247>.
> >>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kamsar/Unicorn/issues/77#issuecomment-154088667>.
>



-- 
Andrei Ungureanu

**Comment by kamsar** [comment]
Looks like GitHub didn't parse your attachment?

**Comment by uandrei** [comment]
Hi,

This is the stack trace:

*Exception Details: *System.InvalidOperationException: Item
/sitecore/content/Demo product is demo/Child of demo too does not exist on
disk.

*Source Error:*

An unhandled exception was generated during the execution of the current
web request. Information regarding the origin and location of the exception
can be identified using the exception stack trace below.
*Stack Trace:*

[InvalidOperationException: Item /sitecore/content/Demo product is
demo/Child of demo too does not exist on disk.]
   Rainbow.Storage.SerializationFileSystemTree.GetChildPaths(IItemMetadata
item) +854
   Rainbow.Storage.SerializationFileSystemTree.GetDescendants(IItemData
root, Boolean ignoreReadErrors) +433
   Rainbow.Storage.SerializationFileSystemTree.Remove(IItemData item) +272
   Rainbow.Storage.SerializationFileSystemDataStore.MoveOrRenameItem(IItemData
itemWithFinalPath, String oldPath) +823
   Unicorn.Data.DataProvider.UnicornDataProvider.SaveItem(ItemDefinition
itemDefinition, ItemChanges changes, CallContext context) +594
   Unicorn.Data.DataProvider.UnicornSqlServerDataProvider.SaveItem(ItemDefinition
itemDefinition, ItemChanges changes, CallContext context) +194
   Sitecore.Data.DataProviders.DataProvider.SaveItem(ItemDefinition
item, ItemChanges changes, CallContext context, DataProviderCollection
providers) +138
   Sitecore.Data.DataSource.SaveItem(ID itemID, ItemChanges changes) +147
   Sitecore.Data.Engines.EngineCommand`2.Execute() +119
   Sitecore.Data.Engines.DataEngine.SaveItem(Item item) +258
   Sitecore.Data.Managers.ItemProvider.SaveItem(Item item) +291
   Sitecore.Data.Items.ItemEditing.AcceptChanges(Boolean
updateStatistics, Boolean silent) +229
   Sitecore.Shell.Framework.Pipelines.RenameItem.Execute(ClientPipelineArgs
args) +602

[TargetInvocationException: Exception has been thrown by the target of
an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[]
arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object
obj, Object[] parameters, Object[] arguments) +76
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags
invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
+211
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +35
   Sitecore.Nexus.Pipelines.NexusPipelineApi.Resume(PipelineArgs args,
Pipeline pipeline) +398
   Sitecore.Web.UI.Sheer.ClientPage.ResumePipeline() +285
   Sitecore.Web.UI.Sheer.ClientPage.OnPreRender(EventArgs e) +504
   Sitecore.Shell.Applications.ContentManager.ContentEditorPage.OnPreRender(EventArgs
e) +25
   System.Web.UI.Control.PreRenderRecursiveInternal() +113
   System.Web.UI.Page.ProcessRequestMain(Boolean
includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
+4297


On 10 November 2015 at 16:51, Kam Figy <notifications@github.com> wrote:

> Looks like GitHub didn't parse your attachment?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kamsar/Unicorn/issues/77#issuecomment-155484077>.
>



-- 
Andrei Ungureanu

**Comment by kamsar** [comment]
This should be fixed, if it's what I think it is, by the commit above. Specifically this would occur:

1. The short path remains the same pre and post move for shortpathed items
2. Moving items first writes the changed items, then deletes the descendants of the old item
3. At the time of the retrieval of descendants the tree is inconsistent and contains both the new and old tree nodes
4. Getting the descendants of the old item is returning partial descendants for the moved item, in cases where the children live in shared short-path parent folders

**Comment by kamsar** [comment]
This is not quite fixed, there is still an issue with moving an item to a parent of its current location. Reopening, will fix that too with a more general fix.

**Comment by kamsar** [comment]
Rainbow 1.0.2-beta01 has been pushed to NuGet. Please update to it and verify that it fixes your problems.
