### ISSUE TITLE
Issue with 2 similarly named template paths

### ISSUE THREAD

**Issue by divamatrix** [kamsar/Unicorn#82]
@divamatrix: nope that's a bug, if you'd like to open an issue on github. I suspect it's using `StartsWith` and not being smart about path segments

Happened with 2 trees:
/sitecore/templates/HRP
/sitecore/templates/HRP-Base

The trees HRP-Base, HRP contained the global path /sitecore/templates/HRP-Base - overlapping trees are not allowed.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: The trees HRP-Base, HRP contained the global path /sitecore/templates/HRP-Base - overlapping trees are not allowed.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[InvalidOperationException: The trees HRP-Base, HRP contained the global path /sitecore/templates/HRP-Base - overlapping trees are not allowed.]
   Rainbow.Storage.SerializationFileSystemDataStore.GetTreeForPath(String path, String database) +361
   Rainbow.Storage.SerializationFileSystemDataStore.FilterDescendantsAndSelf(IItemData root, Func`2 predicate) +170
   Rainbow.Storage.<>c__DisplayClassd.<GetMetadataByTemplateId>b__9(IItemData tree) +53
   System.Linq.Parallel.SelectManyQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, Pair`2& currentKey) +165
   System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork() +77
   System.Linq.Parallel.SpoolingTaskBase.Work() +236
   System.Linq.Parallel.QueryTask.BaseWork(Object unused) +71
   System.Linq.Parallel.<>c__DisplayClass0.<_cctor>b__1(Object o) +42
   System.Threading.Tasks.Task.InnerInvoke() +73
   System.Threading.Tasks.Task.Execute() +61

[AggregateException: One or more errors occurred.]
   System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose) +272
   System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath() +752
   System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNext() +104
   System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext() +38
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +87
   Unicorn.Data.DataProvider.UnicornSqlServerDataProvider.GetTemplateItemIds(CallContext context) +163
   Sitecore.Data.DataProviders.DataProvider.GetTemplateItemIds(CallContext context, DataProviderCollection providers) +71
   Sitecore.Data.Engines.TemplateEngine.AddItemBasedTemplates(TemplateDictionary result) +49
   Sitecore.Data.Engines.TemplateEngine.InternalGetTemplates() +366
   Sitecore.Data.Managers.TemplateProvider.GetTemplates(Database database) +43
   Sitecore.Data.Managers.TemplateManager.GetTemplates(Database database) +24
   Sitecore.Data.TemplateRecords.GetTemplates(Language language) +37
   Synthesis.Configuration.ConfigurationTemplateInputProvider.GetAllTemplates() +82
   Synthesis.Configuration.<ResolveTemplateSpecToItems>d__6.MoveNext() +73
   Synthesis.Configuration.ConfigurationTemplateInputProvider.RefreshSpecTargets() +220
   Synthesis.Configuration.ConfigurationTemplateInputProvider.CreateTemplateList() +49
   Synthesis.Generation.MetadataGenerator.CreateTemplateData() +35
   Synthesis.Generation.MetadataGenerator.GenerateMetadata() +104
   Hawk.Platform.BLL.Synthesis.BaseSiteModelConfiguration.LoadGeneratorParametersProviderFromConfig() +397
   Synthesis.Configuration.ConfigurationProviderConfiguration.get_GeneratorParametersProvider() +92
   Synthesis.Configuration.ConfigurationProviderConfiguration.CreateMetadataGenerator() +31
   Synthesis.Configuration.ConfigurationProviderConfiguration.CreateSyncEngine() +45
   Synthesis.Pipelines.Initialize.CheckModelSynchronization.GetSyncResult(IProviderConfiguration configuration) +86
   Synthesis.Pipelines.Initialize.CheckModelSynchronization.DoLogSync() +90
   Synthesis.Pipelines.Initialize.CheckModelSynchronization.Process(PipelineArgs args) +87
   (Object , Object[] ) +56
   Sitecore.Pipelines.PipelineMethod.Invoke(Object[] parameters) +36
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +361
   Sitecore.Pipelines.CorePipeline.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists) +158
   Sitecore.Nexus.Web.HttpModule.Application_Start() +166
   Sitecore.Nexus.Web.HttpModule.Init(HttpApplication app) +438
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +524
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +176
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +366
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +303

[HttpException (0x80004005): One or more errors occurred.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +773
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +96
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +196

**Comment by kamsar** [comment]
This has been fixed and will be in the next release of Rainbow.
