### ISSUE TITLE
Additional Support for Sitecore Dictionary Items

### ISSUE THREAD

**Issue by GeorgeKarbyn** [kamsar/Unicorn#83]
Sitecore Dictionary Items (created in the Master DB) that are synced do not update the dictionary.dat file. 

The only time the dictionary.dat file gets updated is when you manually save that item in Sitecore. When doing so the ItemEventHandler invokes OnItemSaved and updates the file. 

It almost becomes unmanageable when working with a large team who is working on a multilingual site with a lot of translations. Each time dictionary items are synced, the developer would have to either delete the dictionary.dat file or save each dictionary item manually after the Unicorn sync finished.

**Namespace: Sitecore.Globalization**
**Class: ItemEventHandler**
**Method: OnItemSaved**

:thumbsup:

**Comment by kamsar** [comment]
ok what am I missing here. I figured this would be easy to reproduce but maybe not.

I've:

1) Created a dictionary domain, added an item, referenced that item using `Translate.TextByDomain()` on a cshtml layout
2) Created a global dictionary item (`/system/dictionary/foo` in master), referenced that with `Translate.Text()` on the same layout
3) Published the keys, verified they work in non preview mode
4) Edited the YAML on disk for the keys and changed the value of the translation
5) Run a sync
6) Reload the site in normal mode
7) Note that the key values are updated

Note that I have auto-publish synced items enabled.

**Comment by GeorgeKarbyn** [comment]
This needs to be tested on two different machines.

Key: foo.foo
Phrase: Unicorn

Developer One:
1) Create a Dictionary Item in Sitecore with Key and Phrase.
2) Unicorn should do an auto-sync.
3) Reference Dictionary Item in code with Translate.Text()
3) Check new item and code into source control.

Developer Two:
1) Get latest from Source Control
2) Build
3) Unicorn Sync (adds the Dictionary Item to Sitecore)
4) Publish New Dictionary Item that was pulled from Source Control
5) Refresh web page that references that Dictionary Item.

Result text on website:
    ** Welcome to foo.foo!**

Key shows up instead of Phrase

**Comment by kamsar** [comment]
I was still having problem replicating with the above but I was cheating by having Unicorn create new dictionary entries. I added a handler that dumps the dictionary cache if any dictionary entries are synced, and pushed to NuGet as Unicorn 3.0.3-beta01 (prerelease).

Can you update to that package and verify that it fixes your issue?

**Comment by GeorgeKarbyn** [comment]
I'll see what I can do. Thanks!

**Comment by kamsar** [comment]
Any luck?

**Comment by GeorgeKarbyn** [comment]
So far it seems okay. I'm going to test this out on a larger scale soon.

**Comment by kamsar** [comment]
Excellent. This will go into 3.1, when it comes out. I don't currently have an ETA on that.

**Comment by kamsar** [comment]
This is fixed in 3.1 final.
