### ISSUE TITLE
feature request: add dependency resolving for serialization order 

### ISSUE THREAD

**Issue by dashkodo** [kamsar/Unicorn#85]
We have several unicorn project for one website, 
now we are sync projects in particular order manually

we would like to have automatic or at least manually specified in config dependencies between projects
to run just Sync without parameters

**Comment by dashkodo** [comment]
ooo, i'm forgot about pull requests, looks like it already on approving stage

**Comment by kamsar** [comment]
Correct. Once @Eldblom fixes up the formatting I'll get that merged.

**Comment by Eldblom** [comment]
Sorry. Been pretty busy with Habitat - will get it done this week.
