### ISSUE TITLE
Method 'Flush' does not have an implementation.

### ISSUE THREAD

**Issue by ExerionPL** [kamsar/Unicorn#89]
I have installed Unicorn 3.0.2 through NuGet:
`Package Unicorn -Version 3.0.2`
and after web deployment of the project I have received the following error message:
> Method 'Flush' in type 'Unicorn.Remote.Logging.ProgressReporter' from assembly 'Unicorn.Remote, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by kamsar** [comment]
Do you have a stack trace with that error? Quite odd, as there is no assembly called `Unicorn.Remote` that I recall.

**Comment by ExerionPL** [comment]
No, sorry, I don't have it, my mistake. I wanted to reproduce it this morning, in order to get the stack trace for you, but after I downloaded NuGet package and setup Unicorn for the second time, it was working properly. I think for now, you can consider this ticket a false alarm.
If this problem reappears I will make sure to get the stack trace and will reopen this ticket.
Sorry for the trouble.

**Comment by isurufonseka** [comment]
Got the stack trace here 

[TypeLoadException: Method 'Flush' in type 'Unicorn.Remote.Logging.ProgressReporter' from assembly 'Unicorn.Remote, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.]
   System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType) +0
   System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters() +86
   System.Reflection.RuntimeMethodInfo.GetParametersNoCopy() +16
   System.RuntimeType.FilterApplyMethodBase(MethodBase methodBase, BindingFlags methodFlags, BindingFlags bindingFlags, CallingConventions callConv, Type[] argumentTypes) +72
   System.RuntimeType.GetMethodCandidates(String name, BindingFlags bindingAttr, CallingConventions callConv, Type[] types, Boolean allowPrefixLookup) +255
   System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers) +82
   System.Type.GetMethod(String name, BindingFlags bindingAttr, Binder binder, Type[] types, ParameterModifier[] modifiers) +114
   Sitecore.Reflection.ReflectionUtil.GetMethod(Object obj, String methodName, Object[] parameters) +58
   Sitecore.Pipelines.CoreProcessor.GetMethodInfo(ProcessorObject obj, Object[] parameters) +26
   Sitecore.Pipelines.CoreProcessor.GetMethod(Object[] parameters) +159
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +470
   Sitecore.Nexus.Web.HttpModule.(Object , EventArgs ) +528
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +142
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +92

**Comment by isurufonseka** [comment]
False alarm guys, that namespace is actually from 
https://github.com/BerserkerDotNet/Unicorn.VisualStudio/blob/master/src/Unicorn.Remote/Logging/ProgressReporter.cs

can close this issue.

**Comment by ExerionPL** [comment]
So NuGet via command `Install-Package Unicorn -Version 3.0.2` installs `Unicorn.VisualStudio` from BerserkerDotNet instead of kamsars Unicorn?

**Comment by isurufonseka** [comment]
No don't think so, I think they are unrelated, Do you use the unicorn.visualstudio extension too? 
I'll raise an issue on his repo, looks like it was targeting unicorn 2.xx

**Comment by kamsar** [comment]
Andrii's VS extension is compatible with v3. It no longer requires any
additional package on the unicorn end (it did for 2.x)
