### ISSUE TITLE
Error when field type Layout has a null value

### ISSUE THREAD

**Issue by drachele** [kamsar/Unicorn#90]
Hi,

When trying to sync our content, we are getting this error:

    XmlException: Root element is missing.

We've tracked it down to fields in the .yml file of type ```Layout``` that have a null value, like so:

    - ID: 04bf00db-f5fb-41f7-8ab7-22408372a981
      # __Final Renderings
      Type: Layout
      Value:

If we remove this field from the .yml file, the sync runs without error.

Is there is a fix or workaround for this?

Thanks.

**Comment by GuitarRich** [comment]
Hey @drachele this sounds similar to this issue I had on Rainbow (https://github.com/kamsar/Rainbow/pull/6) - try updating your Rainbow nuget to 1.0.2beta - its marked as pre-release right now. See if that fixes the issue.

**Comment by drachele** [comment]
Hi @GuitarRich,

Unfortunately that hasn't worked for me. I'm now getting a different error on the same items:

```NullReferenceException: Object reference not set to an instance of an object.```

Thanks,
Dan.

**Comment by kamsar** [comment]
@drachele there should be a full stack trace in the Sitecore logs. Can you please post that here?

Also, have any recent changes been made to standard values on the item (or is this itself a standard value item)?

**Comment by drachele** [comment]
Hi @kamsar,

No changes have been made to the standard values on the item, and the item itself is not a standard value item.

It seems to have something to do with the Final Renderings field:


Here is the error from the Sitecore log: [sync_log.txt](https://github.com/kamsar/Unicorn/files/54193/sync_log.txt)

**Comment by kamsar** [comment]
@drachele I have not been able to reproduce this issue directly.

I've tried blanking the __Layout field. I've tried blanking the final layout. I've tried having only final layout. I've copied and pasted the final layout from the english version of the YAML you sent over, to no avail.

However based on the stack trace I was able to make the XML formatter more resilient to bad values. Please give Rainbow 1.0.2-beta02 a shot (from NuGet) - it should eliminate the direct exception. If it's really pulling in invalid XML you may get a secondary exception when Sitecore tries to parse the value.

**Comment by drachele** [comment]
Hi @kamsar,

That doesn't seem to have worked. Am now getting two errors for each item where the __Final Renderings field value is empty:

INNER EXCEPTION
<item path here> (5a9cadde-838a-4b98-8e66-85dcb21ea3d8) (Rainbow.Storage.Sc.Deserialization.DeserializationException)
No stack trace available.
INNER EXCEPTION
Failed to paste item: <item path here> (Rainbow.Storage.Sc.Deserialization.DeserializationException)
at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.Deserialize(IItemData serializedItemData)
   at Unicorn.Evaluators.NewItemOnlyEvaluator.EvaluateNewSerializedItem(IItemData newItemData)
   at Unicorn.Loader.SerializationLoader.DoLoadItem(IItemData serializedItemData, IConsistencyChecker consistencyChecker)
   at Unicorn.Loader.DeserializeFailureRetryer.RetryAll(ISourceDataStore sourceDataStore, Action`1 retrySingleItemAction, Action`1 retryTreeAction)
INNER EXCEPTION
Object reference not set to an instance of an object. (System.NullReferenceException)
at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.PasteField(Item item, IItemFieldValue field, Boolean creatingNewItem)
   at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.PasteVersion(Item item, IItemVersion serializedVersion, Boolean creatingNewItem, List`1 softErrors)
   at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.PasteVersions(IItemData serializedItemData, Item targetItem, Boolean newItemWasCreated, List`1 softErrors)
   at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.Deserialize(IItemData serializedItemData)

**Comment by kamsar** [comment]
Huh very odd. Unfortunately `PasteField` is a quite silly long method so without the pdb to give line numbers it's not much help.

Would it be possible to make a package of the template(s) your sample yaml file is using so I can give it a try with your actual file?

**Comment by kamsar** [comment]
I have made some additional alterations to the way XML fields are handled and posted it to NuGet as Unicorn 3.1-b4 and Rainbow 1.1-b4.

Should you continue to get any error during sync, I have posted the PDBs for this Unicorn/Rainbow version here: https://drive.google.com/file/d/0B2kWVEe9WZ4cNldsWnIwTG5UTDA/view?usp=sharing - if you drop those in your bin folder before reproducing the error you should get line number data in the stack trace when it is written to the log which will be very helpful to me in diagnosis.

Note that some format changes are in Rainbow 1.1. While the item format is backwards compatible, for longer term use it is recommended to sync before the upgrade, then reserialize after upgrading.

**Comment by AlexKasaku** [comment]
Have encountered this issue too, using the stable versions of Unicorn 3.0.2 and Rainbow 1.0.1. Are the beta versions considered stable enough to upgrade to during development?

We can currently workaround by removing the empty Layout field that was serialized in this file.

**Comment by kamsar** [comment]
The current beta of 3.1 is more a RC so yes I'd say stable. There is an
upgrade process however, currently pinned in the unicorn slack channel. I
mean to release it pretty soon.

**Comment by kamsar** [comment]
This is fixed in 3.1 final.
