### ISSUE TITLE
Cannot Duplicate Transparent Sync Item That Doesn't Exist in Database

### ISSUE THREAD

**Issue by williamsk** [kamsar/Unicorn#93]
If you have an item that is part of a transparent sync configuration that only exists on disk (not in the database) - for example, an item created by another team member which you got when you merged their source control branch into your own, if you try to duplicate the item you receive the following error:

```
Server Error in '/' Application.
Existing item to copy was not in the database!
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.InvalidOperationException: Existing item to copy was not in the database!

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:


[InvalidOperationException: Existing item to copy was not in the database!]
   Unicorn.Data.DataProvider.UnicornDataProvider.CopyItem(ItemDefinition source, ItemDefinition destination, String copyName, ID copyId, CallContext context) +386
   Unicorn.Data.DataProvider.UnicornSqlServerDataProvider.CopyItem(ItemDefinition source, ItemDefinition destination, String copyName, ID copyID, CallContext context) +202
   Sitecore.Data.DataProviders.DataProvider.CopyItem(ItemDefinition source, ItemDefinition destination, String copyName, ID copyID, CallContext context, DataProviderCollection providers) +159
   Sitecore.Data.DataSource.CopyItem(ID sourceID, ID destinationID, String copyName, ID copyID) +124
```

(not the full stack trace)

We can usually work around this by sync'ing the configuration or deserializing the item from the developer ribbon, but is there any way to make the duplicate operation work?

**Comment by kamsar** [comment]
Give 3.1.0-beta01 (on NuGet) a shot. Also includes some other new junk like better automated tool authentication and a customizable control panel.

**Comment by williamsk** [comment]
The team that was having this problem decided to stop using Unicorn for the time being and I couldn't talk them into trying the beta out, so I'll take your word for it for now.  If I see it happen on any of my own projects, I'll definitely give the beta a try and let you know.  Thank!
