### ISSUE TITLE
Automated Tool API sample returning auth error

### ISSUE THREAD

**Issue by patoncrispy** [kamsar/Unicorn#94]
I'm trying out your demo ps script of invoking a sync over http. I have my authenticationProvider>SharedSecret (64chars) in my 'App_Config\Include\Unicorn\Unicorn.config' matching the ps script and the URL is valid. However, I keep getting a message saying:

```
Invoke-WebRequest : Access Denied
You need to sign in to Sitecore as an administrator to use the Unicorn control panel.
At{filePath}\scripts\Unicorn.psm1:52 char:12
+     $result = Invoke-WebRequest -Uri $url -TimeoutSec 360 -UseBasicParsing
```

Any ideas what I could be doing wrong?

**Comment by kamsar** [comment]
The docs are too up to date :)

This module only works with unicorn 3.1 beta 1. If you look at history on
the readme.md the previous version will have directions for 3.0.x

**Comment by patoncrispy** [comment]
I went one better and updated Unicorn. Updated the binaries and config files. Getting a bit further this time! 

```
Sync-Unicorn: Preparing authorization for http://{mysite}/unicorn.aspx?verb=Sync&configuration=Serialization
Sync-Unicorn: Received challenge: d3df9ac8-fc42-4fe7-a7d2-b90fac654ecb
Sync-Unicorn: Created signature K4o34/yZqBRYC3SEtq7/MSy8kifZpRKdnEnR3jYC8zsoDkzOrdWZENw5WQncWfhRvjdF4NcMOD+i+XkUcUl1sA==, executing Sync...
Invoke-WebRequest : Access Denied
You need to sign in to Sitecore as an administrator to use the Unicorn control panel.
At D:\{path}\unicorn\scripts\Unicorn.psm1:39 char:12
+     $result = Invoke-WebRequest -Uri $url -Headers @{ "X-MC-MAC" = $signature; "X-M ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExcept
   ion
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by kamsar** [comment]
Hmm. Well that you got a challenge means the auth provider is configured correctly.

You configured the shared secret after upgrading in `Unicorn.UI.config` right? I noticed you mentioned `Unicorn.config` originally. You can use `/sitecore/admin/showconfig.aspx` to verify that Sitecore knows about it.

Verify also that you have MicroCHAP (NuGet), version 1.2 installed. Specifically 1.2. Because it looks like Unicorn is getting confused as to whether you're trying for a tool auth and the HTTP header used changed in 1.2.

If none of that helps, can you capture the HTTP request/response set with Fiddler and attach it here along with your shared secret (feel free to set it to something you don't care about first, just have it be whatever you capture the HTTP with).

**Comment by patoncrispy** [comment]
I checked out the config and the dll versions and all seems fine.

I'm trying to upload my captured Fiddler 4 session (wrapped in a zip file) but GitHub isn't letting me. It keeps telling me to upload it as something else, maybe a zip file! *facepalm*

Is it possible to email it to you?

**Comment by kamsar** [comment]
Sure, my github username at gmail.

**Comment by kamsar** [comment]
I have pushed Unicorn 3.1.0-beta03 which should resolve this issue. It was looking for incorrectly named HTTP headers.

NOTE: due to some formatting changes in this beta, it can read YAML created by earlier versions but it is recommended to sync before upgrading and reserialize after the upgrade to normalize the format. The updated format _cannot_ be read by earlier versions, so if you plan to possibly roll back keep a copy of the pre-upgrade yml files.

**Comment by kamsar** [comment]
This is fixed in 3.1 final.

**Comment by amitthakur2014** [comment]
Hi Kam,
i am running your autodeployment script and getting the below error, with latest unicorn version dll

`Invoke-WebRequest : Server Error in '/' Application.
Object reference not set to an instance of an object. 
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more 
information about the error and where it originated in the code. 
Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.
Source Error: 
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the 
exception can be identified using the exception stack trace below. 
Stack Trace: 
[NullReferenceException: Object reference not set to an instance of an object.]
   Unicorn.ControlPanel.Security.SitecoreDatabaseChallengeStore.AddChallenge(String challenge, Int32 expirationTimeInMsec) +130
   MicroCHAP.Server.ChapServer.GetChallengeToken() +184
   Unicorn.ControlPanel.Pipelines.UnicornControlPanelRequest.ChallengeVerb.CreateResponse(UnicornControlPanelRequestPipelineArgs args) +34
   Unicorn.ControlPanel.Pipelines.UnicornControlPanelRequest.UnicornControlPanelRequestPipelineProcessor.Process(UnicornControlPanelRequestPipe
lineArgs args) +48
   (Object , Object[] ) +82
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +364
   Unicorn.ControlPanel.UnicornControlPanelPipelineProcessor.ProcessRequest(HttpContext context) +417
   Unicorn.ControlPanel.UnicornControlPanelPipelineProcessor.Process(HttpRequestArgs args) +177
   (Object , Object[] ) +82
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +364
   Sitecore.Nexus.Web.HttpModule.(Object , EventArgs ) +456
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +91
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +164
Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34209 
At C:\inetpub\wwwroot\UnicornTest\Website\PS\Unicorn.psm1:52 char:12
+     $result = Invoke-WebRequest -Uri $url -TimeoutSec 360 -UseBasicParsing
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

Attached is my Powershell and config. Also i am using the MicroCHAP.dll which is 1.2.0.0
[PS & Config.zip](https://github.com/kamsar/Unicorn/files/134860/PS.Config.zip)

**Comment by kamsar** [comment]
What unicorn version? There were some recent fixes to the challenge store.

**Comment by amitthakur2014** [comment]
Hi Kamsar,


I am using the Unicorn 3.1.2 DLL.


Regards,

Amit Thakur


________________________________

**Comment by muso31** [comment]
I'm using Unicorn 3.2.0 and microChap 1.2.2.2 and also receive the following error when running the powershell script: 

"Invoke-WebRequest : Access Denied
You need to sign in to Sitecore as an administrator to use the Unicorn control panel"

My shared secret etc are setup correctly. Any ideas? thanks
