### ISSUE TITLE
Question: What is the predicate config element in Unicorn.CustomSerializationFolder.config.example used for?

### ISSUE THREAD

**Issue by agehrke** [kamsar/Unicorn#99]
Hi Kam

In [Unicorn.CustomSerializationFolder.config.example](https://github.com/kamsar/Unicorn/blob/master/src/Unicorn/Standard%20Config%20Files/Unicorn.CustomSerializationFolder.config.example) there's a `predicate` element with path `/sitecore/content/global-settings`. What is this used for?

In [Unicorn.config](https://github.com/kamsar/Unicorn/blob/4845b1272fc3d4b177e88588e6eded5d8f14f9c0/src/Unicorn/Standard%20Config%20Files/Unicorn.config) the `predicate` is defined as:

    
    <predicate type="null"/>

Not sure how this relates..

Andreas

**Comment by kamsar** [comment]
The file used to be a configuration as opposed to patching the base. I forgot to remove the predicate when I converted it.

It's now gone, and thanks for noticing!
